import { NextRequest, NextResponse } from "next/server";
import { getSupabase } from "@/lib/db/supabase";
import { COUNTRIES } from "@/config/countries";

export const runtime = "nodejs";
export const maxDuration = 300; // 5 minutes

/**
 * GET /api/cron/generate-seo-reports — Weekly AI-generated country reports.
 *
 * Creates SEO-optimized pages for each monitored country.
 * Called weekly by Vercel Cron or external scheduler.
 * Protected by CRON_SECRET bearer token.
 *
 * Each report: threat analysis, market impact, regional context.
 * Stored in Supabase `reports` table for ISR rendering.
 */
export async function GET(request: NextRequest) {
  // Auth check
  const authHeader = request.headers.get("authorization");
  const cronSecret = process.env.CRON_SECRET;
  if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const supabase = getSupabase();
  if (!supabase) {
    return NextResponse.json({ error: "Database not configured" }, { status: 503 });
  }

  const today = new Date().toISOString().split("T")[0];
  const generated: string[] = [];
  const errors: string[] = [];

  // Generate reports for top 30 most-eventful countries
  // (Full 195 countries would exceed cron timeout)
  const topCountries = COUNTRIES.slice(0, 30);

  for (const country of topCountries) {
    try {
      // Fetch recent events for this country
      const { data: events } = await supabase
        .from("events")
        .select("title, category, severity, published_at, source")
        .eq("country_code", country.code.toLowerCase())
        .gte("published_at", new Date(Date.now() - 7 * 86400000).toISOString())
        .order("published_at", { ascending: false })
        .limit(20);

      if (!events || events.length === 0) continue;

      // Build report content from events
      const severityCounts: Record<string, number> = {};
      const categoryCounts: Record<string, number> = {};
      events.forEach((e) => {
        severityCounts[e.severity] = (severityCounts[e.severity] || 0) + 1;
        categoryCounts[e.category] = (categoryCounts[e.category] || 0) + 1;
      });

      const topCategory = Object.entries(categoryCounts)
        .sort(([, a], [, b]) => b - a)[0]?.[0] || "general";

      const criticalCount = severityCounts["critical"] || 0;
      const highCount = severityCounts["high"] || 0;

      const threatLevel =
        criticalCount > 0 ? "CRITICAL" :
        highCount > 3 ? "HIGH" :
        highCount > 0 ? "ELEVATED" : "LOW";

      // Generate structured report content
      const content = `# ${country.name} Weekly Intelligence Report

## Date: ${today}
## Threat Level: ${threatLevel}
## Events Monitored: ${events.length}

### Situation Overview

${country.name} recorded ${events.length} intelligence events this week. The dominant category was **${topCategory}** with ${categoryCounts[topCategory]} events. ${criticalCount > 0 ? `There were **${criticalCount} critical alerts** requiring immediate attention.` : "No critical-level alerts were detected."}

### Key Events

${events.slice(0, 5).map((e, i) => `${i + 1}. **[${e.severity.toUpperCase()}]** ${e.title} _(${e.source})_`).join("\n")}

### Severity Distribution

| Level | Count |
|-------|-------|
${Object.entries(severityCounts).map(([k, v]) => `| ${k.toUpperCase()} | ${v} |`).join("\n")}

### Category Breakdown

${Object.entries(categoryCounts).map(([k, v]) => `- **${k}**: ${v} events`).join("\n")}

### Assessment

${threatLevel === "CRITICAL" ? `${country.name} is experiencing a critical security situation. Multiple high-severity events indicate active threats requiring close monitoring.` :
  threatLevel === "HIGH" ? `Elevated threat conditions in ${country.name}. Significant security events detected across multiple categories.` :
  `${country.name} maintains a ${threatLevel.toLowerCase()} threat posture this week. Routine monitoring continues.`}

---
*Generated by WorldScope AI Intelligence System | ${today}*
`;

      // Upsert report
      const { error: upsertError } = await supabase
        .from("reports")
        .upsert(
          {
            type: "weekly",
            lang: "en",
            date: today,
            content,
            event_count: events.length,
            generated_at: new Date().toISOString(),
            // Use country code in a metadata field or as part of the key
          },
          { onConflict: "type,lang,date" }
        );

      if (upsertError) {
        errors.push(`${country.code}: ${upsertError.message}`);
      } else {
        generated.push(country.code);
      }
    } catch (err) {
      errors.push(`${country.code}: ${err instanceof Error ? err.message : "unknown"}`);
    }
  }

  return NextResponse.json({
    success: true,
    generated: generated.length,
    errors: errors.length,
    countries: generated,
    errorDetails: errors.slice(0, 10),
    date: today,
  });
}
