import type { Metadata } from "next";
import { JetBrains_Mono, Inter, Orbitron, Rajdhani, Share_Tech_Mono } from "next/font/google";
import Script from "next/script";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ThemeProvider } from "@/components/shared/ThemeProvider";
import { WebVitals } from "@/components/shared/WebVitals";
import { ScrollToTop } from "@/components/shared/ScrollToTop";
import { ADSENSE_PUB_ID } from "@/config/ads";
import { AdConsentBanner } from "@/components/ads";
import "./globals.css";

/** Self-hosted fonts via next/font — eliminates render-blocking external requests */
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-mono",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-sans",
  display: "swap",
});

/** Theme-specific display fonts — loaded on demand via CSS variable */
const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-orbitron",
  display: "swap",
});

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-rajdhani",
  display: "swap",
});

const shareTechMono = Share_Tech_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-share-tech-mono",
  display: "swap",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://troiamedia.com";

export const metadata: Metadata = {
  title: {
    default: "WorldScope — Global Intelligence Dashboard | TroiaMedia",
    template: "%s | TroiaMedia",
  },
  description:
    "Real-time OSINT dashboard monitoring 195 countries with live conflict maps, cyber threat tracking, flight & vessel data, and AI-powered intelligence briefings.",
  metadataBase: new URL(siteUrl),
  authors: [{ name: "TroiaMedia", url: siteUrl }],
  creator: "TroiaMedia",
  publisher: "TroiaMedia",
  openGraph: {
    title: "WorldScope — Global Intelligence Dashboard | TroiaMedia",
    description:
      "Real-time OSINT dashboard monitoring 195 countries with live conflict maps, cyber threat tracking, flight & vessel data, and AI-powered intelligence briefings.",
    type: "website",
    siteName: "TroiaMedia",
    url: siteUrl,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    site: "@Troiamediacom",
    creator: "@Troiamediacom",
    title: "WorldScope — Global Intelligence Dashboard | TroiaMedia",
    description:
      "Real-time OSINT dashboard monitoring 195 countries with live conflict maps, cyber threat tracking, and AI-powered intelligence briefings.",
    // images auto-generated by opengraph-image.tsx
  },
  keywords: [
    "OSINT dashboard",
    "global intelligence",
    "real-time monitoring",
    "conflict tracker",
    "cyber threat map",
    "WorldScope",
    "threat intelligence",
    "geopolitical risk",
  ],
  robots: { index: true, follow: true },
  verification: {
    google: "FEOfLq44d9PQAQ3SV_Q8DgGXa3jjEdm144ZAPmpMydk",
  },
  alternates: {
    canonical: "/",
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "TroiaMedia",
  },
  other: {
    "mobile-web-app-capable": "yes",
  },
};

/** WebSite + Organization + FAQPage JSON-LD for Google rich results */
const jsonLd = [
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "TroiaMedia",
    url: siteUrl,
    description:
      "Real-time global intelligence dashboard monitoring conflicts, cybersecurity, finance, and geopolitics across 195 countries with 570+ verified sources.",
    potentialAction: {
      "@type": "SearchAction",
      target: `${siteUrl}/country/{search_term_string}`,
      "query-input": "required name=search_term_string",
    },
    inLanguage: ["en", "tr", "ar", "zh", "ja", "ko", "de", "fr", "es", "pt", "ru"],
  },
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "TroiaMedia",
    url: siteUrl,
    logo: `${siteUrl}/icons/icon-512.svg`,
    description:
      "Global intelligence monitoring platform providing real-time event tracking, threat analysis, and geopolitical risk assessment.",
    sameAs: [
      "https://x.com/Troiamediacom",
      "https://troiamedia.bsky.social",
      "https://mastodon.social/@troiamedia",
      "https://github.com/AzadUluyazi",
    ],
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer service",
      url: `${siteUrl}/contact`,
    },
  },
  {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is WorldScope?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "WorldScope is a free real-time global intelligence dashboard by TroiaMedia that monitors geopolitical events, conflicts, cyber threats, financial markets, and more across 195 countries using 570+ verified sources.",
        },
      },
      {
        "@type": "Question",
        name: "Is WorldScope free to use?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes, WorldScope is completely free. All monitoring modules including ARES (conflicts), ATHENA (cybersecurity), HERMES (finance), and others are available at no cost with no account required.",
        },
      },
      {
        "@type": "Question",
        name: "What data sources does WorldScope use?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "WorldScope aggregates data from 570+ verified sources including government agencies, news outlets, OSINT feeds, ADS-B flight data, AIS vessel tracking, weather services, and financial market APIs.",
        },
      },
      {
        "@type": "Question",
        name: "Does WorldScope have an API?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes, WorldScope provides a free public API that requires no authentication. You can access real-time intelligence data, event feeds, and country risk assessments programmatically.",
        },
      },
      {
        "@type": "Question",
        name: "What is OSINT and how does WorldScope use it?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "OSINT (Open Source Intelligence) is intelligence gathered from publicly available sources. WorldScope uses OSINT methodology to aggregate, analyze, and visualize global events in real-time through interactive maps and AI-powered briefings.",
        },
      },
    ],
  },
];

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={`dark ${jetbrainsMono.variable} ${inter.variable} ${orbitron.variable} ${rajdhani.variable} ${shareTechMono.variable}`}>
      <head>
        {/* PWA & Mobile meta */}
        <meta name="theme-color" content="#050a12" />
        <link rel="apple-touch-icon" href="/icons/icon-192.svg" />
        {/* RSS autodiscovery */}
        <link rel="alternate" type="application/rss+xml" title="TroiaMedia RSS Feed" href="/feed.xml" />
        {/* Performance: DNS prefetch + preconnect for external APIs */}
        <link rel="dns-prefetch" href="https://api.mapbox.com" />
        <link rel="dns-prefetch" href="https://img.youtube.com" />
        <link rel="dns-prefetch" href="https://opensky-network.org" />
        <link rel="preconnect" href="https://api.mapbox.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://img.youtube.com" crossOrigin="anonymous" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {ADSENSE_PUB_ID && (
          <Script
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_PUB_ID}`}
            strategy="afterInteractive"
            crossOrigin="anonymous"
          />
        )}
        {/* Plausible Analytics — privacy-friendly, cookie-free */}
        {process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN && (
          <Script
            defer
            data-domain={process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
            src={process.env.NEXT_PUBLIC_PLAUSIBLE_HOST
              ? `${process.env.NEXT_PUBLIC_PLAUSIBLE_HOST}/js/script.js`
              : "https://plausible.io/js/script.js"}
            strategy="afterInteractive"
          />
        )}
      </head>
      <body className="min-h-screen bg-hud-base text-hud-text overflow-hidden">
        {/* Skip to content — accessibility */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[9999] focus:bg-hud-accent focus:text-hud-base focus:px-4 focus:py-2 focus:rounded focus:font-mono focus:text-xs"
        >
          Skip to content
        </a>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider>
            <WebVitals />
            <main id="main-content">
              {children}
            </main>
            <ScrollToTop />
            <AdConsentBanner />
            <div className="scanlines" aria-hidden="true" />
          </ThemeProvider>
        </NextIntlClientProvider>
        {/* Service Worker registration — temporarily disabled for dev */}
        {/* <Script id="sw-register" strategy="lazyOnload">
          {`if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{})}`}
        </Script> */}
      </body>
    </html>
  );
}
