import type { Metadata } from "next";
import { JetBrains_Mono, Inter, Orbitron, Rajdhani, Share_Tech_Mono } from "next/font/google";
import Script from "next/script";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ThemeProvider } from "@/components/shared/ThemeProvider";
import { WebVitals } from "@/components/shared/WebVitals";
import { ScrollToTop } from "@/components/shared/ScrollToTop";
import { ADSENSE_PUB_ID } from "@/config/ads";
import { AdConsentBanner } from "@/components/ads";
import "./globals.css";

/** Self-hosted fonts via next/font — eliminates render-blocking external requests */
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-mono",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-sans",
  display: "swap",
});

/** Theme-specific display fonts — loaded on demand via CSS variable */
const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-orbitron",
  display: "swap",
});

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-rajdhani",
  display: "swap",
});

const shareTechMono = Share_Tech_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-share-tech-mono",
  display: "swap",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://troiamedia.com";

export const metadata: Metadata = {
  title: {
    default: "TroiaMedia — Pantheon Intelligence",
    template: "%s | TroiaMedia",
  },
  description:
    "Real-time global intelligence, finance & technology monitoring platform. Track conflicts, cybersecurity, markets, and geopolitical events worldwide.",
  metadataBase: new URL(siteUrl),
  openGraph: {
    title: "TroiaMedia — Pantheon Intelligence",
    description: "Pantheon-powered global intelligence, conflict & market monitoring.",
    type: "website",
    siteName: "TroiaMedia",
    url: siteUrl,
  },
  twitter: {
    card: "summary_large_image",
    title: "TroiaMedia — Pantheon Intelligence",
    description: "Pantheon-powered global intelligence monitoring platform.",
    // images auto-generated by opengraph-image.tsx
  },
  keywords: [
    // Head — brand & category
    "global intelligence dashboard",
    "OSINT platform",
    "real-time monitoring",
    "WorldScope",
    "TroiaMedia",
    // Body — feature-driven
    "conflict tracker",
    "cyber threat map",
    "live flight tracking",
    "vessel tracking AIS",
    "geopolitical risk",
    "threat intelligence",
    "market monitoring",
    "news aggregator",
    // Long-tail — low competition
    "free OSINT dashboard",
    "real-time conflict map",
    "global threat index",
    "intelligence briefing AI",
    "country risk assessment",
    "live military flight tracker",
    "GPS jamming detection",
    "submarine cable map",
    // High-volume global keywords
    "flight tracker live",
    "live news",
    "OSINT tools",
    "nuclear threat map",
    // Turkish — zero competition
    "küresel istihbarat",
    "gerçek zamanlı izleme",
    "siber güvenlik haritası",
    "çatışma takip",
    "tehdit istihbaratı",
    "OSINT aracı",
    "jeopolitik risk analizi",
  ],
  robots: { index: true, follow: true },
  verification: {
    google: "FEOfLq44d9PQAQ3SV_Q8DgGXa3jjEdm144ZAPmpMydk",
  },
  alternates: {
    canonical: "/",
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "TroiaMedia",
  },
  other: {
    "mobile-web-app-capable": "yes",
  },
};

/** WebSite + Organization JSON-LD for Google rich results */
const jsonLd = [
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "TroiaMedia",
    url: siteUrl,
    description:
      "Real-time global intelligence dashboard monitoring conflicts, cybersecurity, finance, and geopolitics across 195 countries with 570+ verified sources.",
    potentialAction: {
      "@type": "SearchAction",
      target: `${siteUrl}/country/{search_term_string}`,
      "query-input": "required name=search_term_string",
    },
    inLanguage: ["en", "tr", "ar", "zh", "ja", "ko", "de", "fr", "es", "pt", "ru"],
  },
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "TroiaMedia",
    url: siteUrl,
    logo: `${siteUrl}/icons/icon-512.svg`,
    description:
      "Global intelligence monitoring platform providing real-time event tracking, threat analysis, and geopolitical risk assessment.",
    sameAs: [
      "https://x.com/Troiamediacom",
      "https://troiamedia.bsky.social",
      "https://mastodon.social/@troiamedia",
      "https://github.com/AzadUluyazi",
    ],
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer service",
      url: `${siteUrl}/contact`,
    },
  },
];

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={`dark ${jetbrainsMono.variable} ${inter.variable} ${orbitron.variable} ${rajdhani.variable} ${shareTechMono.variable}`}>
      <head>
        {/* PWA & Mobile meta */}
        <meta name="theme-color" content="#050a12" />
        <link rel="apple-touch-icon" href="/icons/icon-192.svg" />
        {/* RSS autodiscovery */}
        <link rel="alternate" type="application/rss+xml" title="TroiaMedia RSS Feed" href="/feed.xml" />
        {/* Performance: DNS prefetch + preconnect for external APIs */}
        <link rel="dns-prefetch" href="https://api.mapbox.com" />
        <link rel="dns-prefetch" href="https://img.youtube.com" />
        <link rel="dns-prefetch" href="https://opensky-network.org" />
        <link rel="preconnect" href="https://api.mapbox.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://img.youtube.com" crossOrigin="anonymous" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {ADSENSE_PUB_ID && (
          <Script
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_PUB_ID}`}
            strategy="lazyOnload"
            crossOrigin="anonymous"
          />
        )}
        {/* Plausible Analytics — privacy-friendly, cookie-free */}
        {process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN && (
          <Script
            defer
            data-domain={process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
            src={process.env.NEXT_PUBLIC_PLAUSIBLE_HOST
              ? `${process.env.NEXT_PUBLIC_PLAUSIBLE_HOST}/js/script.js`
              : "https://plausible.io/js/script.js"}
            strategy="afterInteractive"
          />
        )}
      </head>
      <body className="min-h-screen bg-hud-base text-hud-text overflow-hidden">
        {/* Skip to content — accessibility */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[9999] focus:bg-hud-accent focus:text-hud-base focus:px-4 focus:py-2 focus:rounded focus:font-mono focus:text-xs"
        >
          Skip to content
        </a>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider>
            <WebVitals />
            <main id="main-content">
              {children}
            </main>
            <ScrollToTop />
            <AdConsentBanner />
            <div className="scanlines" aria-hidden="true" />
          </ThemeProvider>
        </NextIntlClientProvider>
        {/* Service Worker registration — temporarily disabled for dev */}
        {/* <Script id="sw-register" strategy="lazyOnload">
          {`if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{})}`}
        </Script> */}
      </body>
    </html>
  );
}
