import type { Category, Severity } from "@/types/intel";

/**
 * Feed configuration type.
 * Feeds are stored in Supabase `feeds` table and fetched at runtime.
 * This file exports types + the seed data for DB initialization.
 */
export interface FeedConfig {
  name: string;
  url: string;
  category: Category;
  defaultSeverity: Severity;
  language?: string;
  region?: string;
}

// ═══════════════════════════════════════════════════════════════════
// SEED DATA — 500+ feeds across 10 categories
// These are used to populate the Supabase `feeds` table.
// At runtime, the /api/intel route reads from DB, not this array.
// ═══════════════════════════════════════════════════════════════════

export const SEED_FEEDS: FeedConfig[] = [
  // ── Conflict & Security (55) ─────────────────────────────────────
  { name: "Reuters World", url: "https://feeds.reuters.com/Reuters/worldNews", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "BBC World", url: "https://feeds.bbci.co.uk/news/world/rss.xml", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "AP News", url: "https://rsshub.app/apnews/topics/world-news", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "Defense One", url: "https://www.defenseone.com/rss/", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "War on the Rocks", url: "https://warontherocks.com/feed/", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "Janes Defence", url: "https://www.janes.com/feeds/news", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "Liveuamap", url: "https://liveuamap.com/rss", category: "conflict", defaultSeverity: "high", region: "europe" },
  { name: "Anadolu Agency EN", url: "https://www.aa.com.tr/en/rss/default?cat=world", category: "conflict", defaultSeverity: "medium", region: "turkey" },
  { name: "CNN World", url: "https://rss.cnn.com/rss/edition_world.rss", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "NPR World", url: "https://feeds.npr.org/1004/rss.xml", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "PBS NewsHour", url: "https://www.pbs.org/newshour/feeds/rss/headlines", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "ABC News International", url: "https://feeds.abcnews.com/abcnews/internationalheadlines", category: "conflict", defaultSeverity: "medium", region: "us" },
  { name: "NBC News World", url: "https://feeds.nbcnews.com/nbcnews/public/world", category: "conflict", defaultSeverity: "medium", region: "us" },
  { name: "CBS News World", url: "https://www.cbsnews.com/latest/rss/world", category: "conflict", defaultSeverity: "medium", region: "us" },
  { name: "The Guardian World", url: "https://www.theguardian.com/world/rss", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "NY Times World", url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "Washington Post World", url: "https://feeds.washingtonpost.com/rss/world", category: "conflict", defaultSeverity: "medium", region: "us" },
  { name: "Sky News World", url: "https://feeds.skynews.com/feeds/rss/world.xml", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "The Independent World", url: "https://www.independent.co.uk/news/world/rss", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "France 24", url: "https://www.france24.com/en/rss", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "Euronews", url: "https://www.euronews.com/rss?format=xml", category: "conflict", defaultSeverity: "medium", region: "europe" },
  { name: "DW News", url: "https://rss.dw.com/xml/rss-en-all", category: "conflict", defaultSeverity: "medium", region: "europe" },
  { name: "WSJ World", url: "https://feeds.content.dowjones.io/public/rss/RSSWorldNews", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "The War Zone", url: "https://www.twz.com/feed", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "Defense News", url: "https://www.defensenews.com/arc/outboundfeeds/rss/", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "Military Times", url: "https://www.militarytimes.com/arc/outboundfeeds/rss/", category: "conflict", defaultSeverity: "high", region: "us" },
  { name: "Task & Purpose", url: "https://taskandpurpose.com/feed/", category: "conflict", defaultSeverity: "medium", region: "us" },
  { name: "USNI News", url: "https://news.usni.org/feed", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "Oryx OSINT", url: "https://www.oryxspioenkop.com/feeds/posts/default?alt=rss", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "Arms Control Association", url: "https://www.armscontrol.org/rss.xml", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "IISS", url: "https://www.iiss.org/rss", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "SIPRI", url: "https://www.sipri.org/rss.xml", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "ITIC Terrorism Info", url: "https://www.terrorism-info.org.il/en/feed/", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "NATO News", url: "https://www.nato.int/cps/en/natolive/news.xml", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "Interpol News", url: "https://www.interpol.int/en/News-and-Events/News/RSS", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "Europol", url: "https://www.europol.europa.eu/rss.xml", category: "conflict", defaultSeverity: "medium", region: "europe" },
  { name: "OPCW Chemical Weapons", url: "https://www.opcw.org/rss.xml", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "Jamestown Foundation", url: "https://jamestown.org/feed/", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "Channel NewsAsia", url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "The Hindu International", url: "https://www.thehindu.com/news/international/feeder/default.rss", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Kyodo News", url: "https://english.kyodonews.net/rss/all.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "NHK World", url: "https://www3.nhk.or.jp/nhkworld/en/news/feeds/", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Yonhap News", url: "https://en.yna.co.kr/RSS/news.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "News24 South Africa", url: "https://feeds.news24.com/articles/news24/TopStories/rss", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Africanews", url: "https://www.africanews.com/feed/", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Infobae", url: "https://www.infobae.com/arc/outboundfeeds/rss/", category: "conflict", defaultSeverity: "medium", region: "latam" },
  { name: "Middle East Eye", url: "https://www.middleeasteye.net/rss", category: "conflict", defaultSeverity: "medium", region: "mideast" },
  { name: "Times of Israel", url: "https://www.timesofisrael.com/feed/", category: "conflict", defaultSeverity: "medium", region: "mideast" },
  { name: "Al Arabiya", url: "https://english.alarabiya.net/tools/rss", category: "conflict", defaultSeverity: "medium", region: "mideast" },
  { name: "TASS", url: "https://tass.com/rss/v2.xml", category: "conflict", defaultSeverity: "medium", region: "russia" },
  { name: "Meduza", url: "https://meduza.io/rss/en/all", category: "conflict", defaultSeverity: "medium", region: "russia" },
  { name: "Hurriyet Daily News", url: "https://www.hurriyetdailynews.com/rss", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "TRT Haber", url: "https://www.trthaber.com/xml_mobile.rss", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "gCaptain Maritime", url: "https://gcaptain.com/feed/", category: "conflict", defaultSeverity: "medium", region: "global" },

  // ── Finance & Economy (19) ───────────────────────────────────────
  { name: "Reuters Business", url: "https://feeds.reuters.com/reuters/businessNews", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "CNBC Top News", url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114", category: "finance", defaultSeverity: "low", region: "us" },
  { name: "Bloomberg Markets", url: "https://feeds.bloomberg.com/markets/news.rss", category: "finance", defaultSeverity: "medium", region: "global" },
  { name: "Financial Times", url: "https://www.ft.com/rss/home", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "MarketWatch", url: "https://feeds.marketwatch.com/marketwatch/topstories/", category: "finance", defaultSeverity: "low", region: "us" },
  { name: "Investing.com", url: "https://www.investing.com/rss/news.rss", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Yahoo Finance", url: "https://finance.yahoo.com/news/rssindex", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Seeking Alpha", url: "https://seekingalpha.com/market_currents.xml", category: "finance", defaultSeverity: "low", region: "us" },
  { name: "WSJ US Business", url: "https://feeds.content.dowjones.io/public/rss/RSSUSnews", category: "finance", defaultSeverity: "low", region: "us" },
  { name: "CoinDesk", url: "https://www.coindesk.com/arc/outboundfeeds/rss/", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Cointelegraph", url: "https://cointelegraph.com/rss", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "The Economist Finance", url: "https://www.economist.com/finance-and-economics/rss.xml", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "ZeroHedge", url: "https://www.zerohedge.com/fullrss2.xml", category: "finance", defaultSeverity: "medium", region: "global" },
  { name: "Federal Reserve", url: "https://www.federalreserve.gov/feeds/press_all.xml", category: "finance", defaultSeverity: "medium", region: "us" },
  { name: "SEC Press Releases", url: "https://www.sec.gov/news/pressreleases.rss", category: "finance", defaultSeverity: "low", region: "us" },
  { name: "ECB Press", url: "https://www.ecb.europa.eu/rss/press.html", category: "finance", defaultSeverity: "medium", region: "europe" },
  { name: "IMF News", url: "https://www.imf.org/en/News/Rss", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Hellenic Shipping News", url: "https://www.hellenicshippingnews.com/feed/", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Splash Maritime", url: "https://splash247.com/feed/", category: "finance", defaultSeverity: "low", region: "global" },

  // ── Finance Extended: Forex, Bonds, Commodities, Crypto (from reference repo) ──
  // Forex & Currencies
  { name: "Forex News (GN)", url: "https://news.google.com/rss/search?q=(%22forex%22+OR+%22currency%22+OR+%22FX+market%22)+trading+when:1d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Dollar Watch (GN)", url: "https://news.google.com/rss/search?q=(%22dollar+index%22+OR+DXY+OR+%22US+dollar%22+OR+%22euro+dollar%22)+when:2d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Central Bank Rates (GN)", url: "https://news.google.com/rss/search?q=(%22central+bank%22+OR+%22interest+rate%22+OR+%22rate+decision%22+OR+%22monetary+policy%22)+when:2d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "global" },
  // Fixed Income
  { name: "Bond Market (GN)", url: "https://news.google.com/rss/search?q=(%22bond+market%22+OR+%22treasury+yields%22+OR+%22bond+yields%22+OR+%22fixed+income%22)+when:2d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Treasury Watch (GN)", url: "https://news.google.com/rss/search?q=(%22US+Treasury%22+OR+%22Treasury+auction%22+OR+%2210-year+yield%22)+when:2d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "us" },
  // Commodities
  { name: "Oil & Gas (GN)", url: "https://news.google.com/rss/search?q=(oil+price+OR+OPEC+OR+%22natural+gas%22+OR+%22crude+oil%22+OR+WTI+OR+Brent)+when:1d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "global" },
  { name: "Gold & Metals (GN)", url: "https://news.google.com/rss/search?q=(gold+price+OR+silver+price+OR+copper+OR+platinum+OR+%22precious+metals%22)+when:2d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Commodity Trading (GN)", url: "https://news.google.com/rss/search?q=(%22commodity+trading%22+OR+%22futures+market%22+OR+CME+OR+NYMEX+OR+COMEX)+when:2d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  // Crypto Extended
  { name: "The Block (GN)", url: "https://news.google.com/rss/search?q=site:theblock.co+when:1d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "DeFi News (GN)", url: "https://news.google.com/rss/search?q=(DeFi+OR+%22decentralized+finance%22+OR+DEX+OR+%22yield+farming%22)+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  // Central Banks Extended
  { name: "ECB Watch (GN)", url: "https://news.google.com/rss/search?q=(%22European+Central+Bank%22+OR+ECB+OR+Lagarde)+monetary+policy+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "europe" },
  { name: "BoJ Watch (GN)", url: "https://news.google.com/rss/search?q=(%22Bank+of+Japan%22+OR+BoJ)+monetary+policy+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "asia" },
  { name: "BoE Watch (GN)", url: "https://news.google.com/rss/search?q=(%22Bank+of+England%22+OR+BoE)+monetary+policy+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "europe" },
  { name: "PBoC Watch (GN)", url: "https://news.google.com/rss/search?q=(%22People%27s+Bank+of+China%22+OR+PBoC+OR+PBOC)+when:7d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "asia" },
  // Economic Data
  { name: "Economic Data (GN)", url: "https://news.google.com/rss/search?q=(CPI+OR+inflation+OR+GDP+OR+%22jobs+report%22+OR+%22nonfarm+payrolls%22+OR+PMI)+when:2d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "global" },
  { name: "Trade & Tariffs (GN)", url: "https://news.google.com/rss/search?q=(tariff+OR+%22trade+war%22+OR+%22trade+deficit%22+OR+sanctions)+when:2d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "global" },
  // IPOs & M&A
  { name: "IPO News (GN)", url: "https://news.google.com/rss/search?q=(IPO+OR+%22initial+public+offering%22+OR+SPAC+OR+%22direct+listing%22)+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Earnings Reports (GN)", url: "https://news.google.com/rss/search?q=(%22earnings+report%22+OR+%22quarterly+earnings%22+OR+%22revenue+beat%22+OR+%22earnings+miss%22)+when:2d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "M&A News (GN)", url: "https://news.google.com/rss/search?q=(%22merger%22+OR+%22acquisition%22+OR+%22takeover+bid%22+OR+%22buyout%22)+billion+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "medium", region: "global" },
  // Regulation
  { name: "Financial Regulation (GN)", url: "https://news.google.com/rss/search?q=(SEC+OR+CFTC+OR+FINRA+OR+FCA)+regulation+OR+enforcement+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Crypto Regulation (GN)", url: "https://news.google.com/rss/search?q=(crypto+regulation+OR+%22digital+asset%22+regulation+OR+%22stablecoin%22+regulation)+when:7d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  // Institutional
  { name: "Hedge Fund News (GN)", url: "https://news.google.com/rss/search?q=(%22hedge+fund%22+OR+%22Bridgewater%22+OR+%22Citadel%22+OR+%22Renaissance%22)+when:7d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Private Equity (GN)", url: "https://news.google.com/rss/search?q=(%22private+equity%22+OR+Blackstone+OR+KKR+OR+Apollo+OR+Carlyle)+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  // GCC Business
  { name: "Arabian Business (GN)", url: "https://news.google.com/rss/search?q=site:arabianbusiness.com+(Saudi+Arabia+OR+UAE+OR+GCC)+when:7d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "middle-east" },
  { name: "Gulf Investments (GN)", url: "https://news.google.com/rss/search?q=(%22Saudi+Arabia%22+OR+%22UAE%22+OR+%22Abu+Dhabi%22)+investment+infrastructure+when:7d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "middle-east" },
  // Market Analysis
  { name: "Market Outlook (GN)", url: "https://news.google.com/rss/search?q=(%22market+outlook%22+OR+%22stock+market+forecast%22+OR+%22bull+market%22+OR+%22bear+market%22)+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Bank Research (GN)", url: "https://news.google.com/rss/search?q=(%22Goldman+Sachs%22+OR+%22JPMorgan%22+OR+%22Morgan+Stanley%22)+forecast+OR+outlook+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Nikkei Asia Markets (GN)", url: "https://news.google.com/rss/search?q=site:asia.nikkei.com+markets+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "low", region: "asia" },
  // Fintech
  { name: "Fintech News (GN)", url: "https://news.google.com/rss/search?q=(fintech+OR+%22payment+technology%22+OR+%22neobank%22+OR+%22digital+banking%22)+when:3d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "info", region: "global" },
  { name: "Blockchain Finance (GN)", url: "https://news.google.com/rss/search?q=(%22blockchain+finance%22+OR+%22tokenization%22+OR+%22digital+securities%22+OR+CBDC)+when:7d&hl=en-US&gl=US&ceid=US:en", category: "finance", defaultSeverity: "info", region: "global" },

  // ── Diplomacy & Policy (16) ──────────────────────────────────────
  { name: "Foreign Affairs", url: "https://www.foreignaffairs.com/rss.xml", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "The Diplomat", url: "https://thediplomat.com/feed/", category: "diplomacy", defaultSeverity: "low", region: "asia" },
  { name: "European Council", url: "https://www.consilium.europa.eu/en/rss/", category: "diplomacy", defaultSeverity: "low", region: "europe" },
  { name: "UN News", url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "Daily Sabah", url: "https://www.dailysabah.com/rssFeed/home", category: "diplomacy", defaultSeverity: "low", region: "turkey" },
  { name: "Foreign Policy", url: "https://foreignpolicy.com/feed/", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "Atlantic Council", url: "https://www.atlanticcouncil.org/feed/", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "CSIS", url: "https://www.csis.org/rss.xml", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "Brookings Institution", url: "https://www.brookings.edu/feed/", category: "diplomacy", defaultSeverity: "low", region: "global" },
  { name: "Politico", url: "https://rss.politico.com/politics-news.xml", category: "diplomacy", defaultSeverity: "low", region: "us" },
  { name: "The Hill", url: "https://thehill.com/news/feed/", category: "diplomacy", defaultSeverity: "low", region: "us" },
  { name: "Chatham House", url: "https://www.chathamhouse.org/rss.xml", category: "diplomacy", defaultSeverity: "low", region: "global" },
  { name: "Carnegie Endowment", url: "https://carnegieendowment.org/rss/solr.xml", category: "diplomacy", defaultSeverity: "low", region: "global" },
  { name: "RAND Corporation", url: "https://www.rand.org/content/rand/blog.xml", category: "diplomacy", defaultSeverity: "low", region: "global" },
  { name: "CFR", url: "https://www.cfr.org/rss.xml", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "US State Dept", url: "https://www.state.gov/rss-feed/press-releases/feed/", category: "diplomacy", defaultSeverity: "medium", region: "us" },

  // ── Cyber Security (14) ──────────────────────────────────────────
  { name: "Krebs on Security", url: "https://krebsonsecurity.com/feed/", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "The Hacker News", url: "https://feeds.feedburner.com/TheHackersNews", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "BleepingComputer", url: "https://www.bleepingcomputer.com/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Dark Reading", url: "https://www.darkreading.com/rss.xml", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Threatpost", url: "https://threatpost.com/feed/", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "US-CERT Alerts", url: "https://www.cisa.gov/uscert/ncas/alerts.xml", category: "cyber", defaultSeverity: "critical", region: "us" },
  { name: "CISA Advisories", url: "https://www.cisa.gov/cybersecurity-advisories/all.xml", category: "cyber", defaultSeverity: "high", region: "us" },
  { name: "Schneier on Security", url: "https://www.schneier.com/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "SecurityWeek", url: "https://www.securityweek.com/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Recorded Future", url: "https://www.recordedfuture.com/feed", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Cisco Talos", url: "https://blog.talosintelligence.com/feeds/posts/default?alt=rss", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Kaspersky Securelist", url: "https://securelist.com/feed/", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Mandiant Blog", url: "https://www.mandiant.com/resources/blog/rss.xml", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Palo Alto Unit 42", url: "https://unit42.paloaltonetworks.com/feed/", category: "cyber", defaultSeverity: "high", region: "global" },

  // ── Technology (13) ──────────────────────────────────────────────
  { name: "TechCrunch", url: "https://techcrunch.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "The Verge", url: "https://www.theverge.com/rss/index.xml", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Wired", url: "https://www.wired.com/feed/rss", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "MIT Technology Review", url: "https://www.technologyreview.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Hacker News", url: "https://hnrss.org/frontpage", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "VentureBeat", url: "https://venturebeat.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "GitHub Blog", url: "https://github.blog/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Dev.to", url: "https://dev.to/feed", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "IEEE Spectrum", url: "https://spectrum.ieee.org/feeds/feed.rss", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "SpaceX Missions", url: "https://www.spacex.com/api/mission/rss", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "NASA News", url: "https://www.nasa.gov/news-release/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "ESA Space Safety", url: "https://www.esa.int/rssfeed/Our_Activities/Space_Safety", category: "tech", defaultSeverity: "info", region: "global" },

  // ── Energy & Nuclear (8) ─────────────────────────────────────────
  { name: "OilPrice.com", url: "https://oilprice.com/rss/main", category: "energy", defaultSeverity: "medium", region: "global" },
  { name: "Energy Intelligence", url: "https://www.energyintel.com/rss", category: "energy", defaultSeverity: "medium", region: "global" },
  { name: "Rigzone", url: "https://www.rigzone.com/news/rss/rigzone_latest.aspx", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "IAEA Nuclear", url: "https://www.iaea.org/feeds/press-releases", category: "energy", defaultSeverity: "high", region: "global" },
  { name: "US NRC Nuclear", url: "https://www.nrc.gov/public-involve/listserver/rss-feeds/news-nhq.xml", category: "energy", defaultSeverity: "medium", region: "us" },
  { name: "World Nuclear News", url: "https://www.world-nuclear-news.org/feed", category: "energy", defaultSeverity: "medium", region: "global" },
  { name: "Renewables Now", url: "https://renewablesnow.com/news/rss/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "S&P Global Oil", url: "https://www.spglobal.com/commodityinsights/en/rss-feed/oil", category: "energy", defaultSeverity: "medium", region: "global" },

  // ── Health & Pandemic (8) ────────────────────────────────────────
  { name: "WHO News", url: "https://www.who.int/rss-feeds/news-english.xml", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "CDC Newsroom", url: "https://tools.cdc.gov/podcasts/feed.asp?feedid=183", category: "health", defaultSeverity: "medium", region: "us" },
  { name: "ProMED", url: "https://promedmail.org/feed/", category: "health", defaultSeverity: "high", region: "global" },
  { name: "ECDC News", url: "https://www.ecdc.europa.eu/en/rss.xml", category: "health", defaultSeverity: "medium", region: "europe" },
  { name: "STAT News Health", url: "https://www.statnews.com/feed/", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "CIDRAP", url: "https://www.cidrap.umn.edu/rss.xml", category: "health", defaultSeverity: "high", region: "global" },
  { name: "The Lancet", url: "https://www.thelancet.com/rssfeed/lancet_current.xml", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "Red Cross ICRC", url: "https://www.icrc.org/en/rss", category: "health", defaultSeverity: "medium", region: "global" },

  // ── Natural Disasters (5) ────────────────────────────────────────
  { name: "USGS Earthquakes", url: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.atom", category: "natural", defaultSeverity: "high", region: "global" },
  { name: "GDACS", url: "https://www.gdacs.org/xml/rss.xml", category: "natural", defaultSeverity: "high", region: "global" },
  { name: "ReliefWeb Updates", url: "https://reliefweb.int/updates/rss.xml", category: "natural", defaultSeverity: "medium", region: "global" },
  { name: "NOAA Weather Alerts", url: "https://alerts.weather.gov/cap/us.php?x=1", category: "natural", defaultSeverity: "medium", region: "us" },
  { name: "Volcano Discovery", url: "https://www.volcanodiscovery.com/rss/news.xml", category: "natural", defaultSeverity: "medium", region: "global" },

  // ── Aviation (5) ─────────────────────────────────────────────────
  { name: "Aviation Herald", url: "https://avherald.com/h?list=0&feed=1", category: "aviation", defaultSeverity: "medium", region: "global" },
  { name: "FlightGlobal", url: "https://www.flightglobal.com/rss", category: "aviation", defaultSeverity: "low", region: "global" },
  { name: "Simple Flying", url: "https://simpleflying.com/feed/", category: "aviation", defaultSeverity: "info", region: "global" },
  { name: "AIN Online Aviation", url: "https://www.ainonline.com/feed", category: "aviation", defaultSeverity: "low", region: "global" },
  { name: "The Points Guy Aviation", url: "https://thepointsguy.com/feed/", category: "aviation", defaultSeverity: "info", region: "global" },

  // ── Protest & Human Rights (4) ───────────────────────────────────
  { name: "ACLED", url: "https://acleddata.com/feed/", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "Crisis Group", url: "https://www.crisisgroup.org/feed", category: "protest", defaultSeverity: "high", region: "global" },
  { name: "Human Rights Watch", url: "https://www.hrw.org/rss/publications", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "Amnesty International", url: "https://www.amnesty.org/en/feed/", category: "protest", defaultSeverity: "medium", region: "global" },

  // ═══════════════════════════════════════════════════════════════════
  // EXPANSION WAVE 2 — 160+ additional feeds
  // ═══════════════════════════════════════════════════════════════════

  // ── Conflict & OSINT Expansion (30) ────────────────────────────────
  { name: "ISW", url: "https://www.understandingwar.org/rss.xml", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "Bellingcat", url: "https://www.bellingcat.com/feed/", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "IntelBrief", url: "https://www.theintelbrief.com/feed/", category: "conflict", defaultSeverity: "medium", region: "global" },
  { name: "Long War Journal", url: "https://www.longwarjournal.org/feed", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "IHS Conflict Monitor", url: "https://ihsmarkit.com/rss/conflict.xml", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "South China Morning Post", url: "https://www.scmp.com/rss/91/feed", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Nikkei Asia", url: "https://asia.nikkei.com/rss/feed/nar", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Jakarta Post", url: "https://www.thejakartapost.com/feed", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Straits Times", url: "https://www.straitstimes.com/news/asia/rss.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Dawn Pakistan", url: "https://www.dawn.com/feed", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Manorama Online", url: "https://www.onmanorama.com/news.feed", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Iran International", url: "https://www.iranintl.com/en/feed", category: "conflict", defaultSeverity: "medium", region: "mideast" },
  { name: "Kurdistan24", url: "https://www.kurdistan24.net/en/rss", category: "conflict", defaultSeverity: "medium", region: "mideast" },
  { name: "The National UAE", url: "https://www.thenationalnews.com/rss", category: "conflict", defaultSeverity: "medium", region: "mideast" },
  { name: "New Arab", url: "https://www.newarab.com/rss", category: "conflict", defaultSeverity: "medium", region: "mideast" },
  { name: "Vanguard Nigeria", url: "https://www.vanguardngr.com/feed/", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Daily Nation Kenya", url: "https://www.nation.co.ke/rss", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Mail & Guardian SA", url: "https://mg.co.za/feed/", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Sahara Reporters", url: "https://saharareporters.com/feed", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Colombia Reports", url: "https://colombiareports.com/feed/", category: "conflict", defaultSeverity: "medium", region: "latam" },
  { name: "Buenos Aires Times", url: "https://www.batimes.com.ar/feed", category: "conflict", defaultSeverity: "medium", region: "latam" },
  { name: "Mexico News Daily", url: "https://mexiconewsdaily.com/feed/", category: "conflict", defaultSeverity: "medium", region: "latam" },
  { name: "Rappler Philippines", url: "https://www.rappler.com/feed/", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "VNExpress International", url: "https://e.vnexpress.net/rss/news.rss", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Bangkok Post", url: "https://www.bangkokpost.com/rss/data/topstories.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Moscow Times", url: "https://www.themoscowtimes.com/rss/news", category: "conflict", defaultSeverity: "medium", region: "russia" },
  { name: "Kyiv Independent", url: "https://kyivindependent.com/feed/", category: "conflict", defaultSeverity: "high", region: "europe" },
  { name: "Balkan Insight", url: "https://balkaninsight.com/feed/", category: "conflict", defaultSeverity: "medium", region: "europe" },
  { name: "Defense Blog", url: "https://defence-blog.com/feed/", category: "conflict", defaultSeverity: "high", region: "global" },
  { name: "Naval News", url: "https://www.navalnews.com/feed/", category: "conflict", defaultSeverity: "medium", region: "global" },

  // ── Cyber Security Expansion (25) ──────────────────────────────────
  { name: "NIST NVD", url: "https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss.xml", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Exploit Database", url: "https://www.exploit-db.com/rss.xml", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Packet Storm", url: "https://rss.packetstormsecurity.com/", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Zero Day Initiative", url: "https://www.zerodayinitiative.com/rss/published/", category: "cyber", defaultSeverity: "critical", region: "global" },
  { name: "SANS ISC", url: "https://isc.sans.edu/rssfeed_full.xml", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Sophos Naked Security", url: "https://nakedsecurity.sophos.com/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "ESET WeLiveSecurity", url: "https://www.welivesecurity.com/en/rss/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Malwarebytes Labs", url: "https://www.malwarebytes.com/blog/feed/index.xml", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "SentinelOne", url: "https://www.sentinelone.com/feed/", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "CrowdStrike Blog", url: "https://www.crowdstrike.com/blog/feed/", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Microsoft Security", url: "https://www.microsoft.com/security/blog/feed/", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Google Project Zero", url: "https://googleprojectzero.blogspot.com/feeds/posts/default?alt=rss", category: "cyber", defaultSeverity: "critical", region: "global" },
  { name: "Wordfence", url: "https://www.wordfence.com/blog/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "HackerOne Hacktivity", url: "https://hackerone.com/hacktivity.rss", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Infosecurity Magazine", url: "https://www.infosecurity-magazine.com/rss/news/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "SC Magazine", url: "https://www.scmagazine.com/feed", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Cyberscoop", url: "https://cyberscoop.com/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Dragos ICS", url: "https://www.dragos.com/feed/", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Rapid7 Blog", url: "https://blog.rapid7.com/rss/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Qualys Blog", url: "https://blog.qualys.com/feed", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "TrendMicro", url: "https://www.trendmicro.com/en_us/research.rss.html", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "NCSC UK", url: "https://www.ncsc.gov.uk/api/1/services/v1/report-rss-feed.xml", category: "cyber", defaultSeverity: "high", region: "europe" },
  { name: "BSI Germany", url: "https://www.bsi.bund.de/SiteGlobals/Functions/RSSFeed/RSSNewsfeed/RSSNewsfeed_en.xml", category: "cyber", defaultSeverity: "medium", region: "europe" },
  { name: "CERT-EU", url: "https://cert.europa.eu/publications/security-advisories/rss", category: "cyber", defaultSeverity: "high", region: "europe" },
  { name: "JPCERT", url: "https://www.jpcert.or.jp/english/rss/jpcert-en.rdf", category: "cyber", defaultSeverity: "high", region: "asia" },

  // ── Technology Expansion (25) ──────────────────────────────────────
  { name: "AI News", url: "https://www.artificialintelligence-news.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "The AI Blog", url: "https://blogs.microsoft.com/ai/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Google AI Blog", url: "https://blog.google/technology/ai/rss/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "OpenAI Blog", url: "https://openai.com/blog/rss/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Anthropic Research", url: "https://www.anthropic.com/feed", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "DeepMind Blog", url: "https://deepmind.google/blog/rss.xml", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "SemiAnalysis", url: "https://www.semianalysis.com/feed", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Tom's Hardware", url: "https://www.tomshardware.com/feeds/all", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "AnandTech", url: "https://www.anandtech.com/rss/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Protocol", url: "https://www.protocol.com/feeds/feed.rss", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Rest of World", url: "https://restofworld.org/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Platformer", url: "https://www.platformer.news/rss/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "404 Media", url: "https://www.404media.co/rss/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "The Information", url: "https://www.theinformation.com/feed", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "SpaceNews", url: "https://spacenews.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Quantum Computing Report", url: "https://quantumcomputingreport.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Semiconductor Engineering", url: "https://semiengineering.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "EE Times", url: "https://www.eetimes.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Next Platform", url: "https://www.nextplatform.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Engadget", url: "https://www.engadget.com/rss.xml", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "ZDNet", url: "https://www.zdnet.com/news/rss.xml", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "9to5Google", url: "https://9to5google.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "9to5Mac", url: "https://9to5mac.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "MacRumors", url: "https://feeds.macrumors.com/MacRumors-All", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Android Authority", url: "https://www.androidauthority.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },

  // ── Finance Expansion (20) ─────────────────────────────────────────
  { name: "Bank of England", url: "https://www.bankofengland.co.uk/rss/news", category: "finance", defaultSeverity: "medium", region: "europe" },
  { name: "Bank of Japan", url: "https://www.boj.or.jp/en/rss/whatsnew.xml", category: "finance", defaultSeverity: "medium", region: "asia" },
  { name: "RBA Australia", url: "https://www.rba.gov.au/rss/rss-cb-media-releases.xml", category: "finance", defaultSeverity: "medium", region: "asia" },
  { name: "PBOC China", url: "https://www.pbc.gov.cn/english/rss/130437.xml", category: "finance", defaultSeverity: "medium", region: "asia" },
  { name: "TCMB Turkey", url: "https://www.tcmb.gov.tr/wps/wcm/connect/tcmb+en/tcmb+en/main+menu/announcements/rss", category: "finance", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "DeFi Pulse", url: "https://defipulse.com/blog/feed/", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "The Block", url: "https://www.theblock.co/rss.xml", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Decrypt", url: "https://decrypt.co/feed", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Commodity Markets (World Bank)", url: "https://blogs.worldbank.org/en/category/commodity-markets/feed", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Gold.org", url: "https://www.gold.org/goldhub/feed", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Nikkei Markets", url: "https://asia.nikkei.com/rss/feed/nar?category=Markets", category: "finance", defaultSeverity: "low", region: "asia" },
  { name: "Financial Express India", url: "https://www.financialexpress.com/feed/", category: "finance", defaultSeverity: "low", region: "asia" },
  { name: "Borsa Istanbul News", url: "https://www.borsaistanbul.com/en/sayfa/2241/rss-feeds", category: "finance", defaultSeverity: "low", language: "tr", region: "turkey" },
  { name: "Barron's", url: "https://www.barrons.com/market-data/feeds/rss/", category: "finance", defaultSeverity: "low", region: "us" },
  { name: "Motley Fool", url: "https://www.fool.com/feeds/index.aspx", category: "finance", defaultSeverity: "info", region: "us" },
  { name: "Forex Factory News", url: "https://www.forexfactory.com/feed.php", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "DailyFX", url: "https://www.dailyfx.com/feeds/market-news", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "FXStreet", url: "https://www.fxstreet.com/rss", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Kitco News", url: "https://www.kitco.com/rss/", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Oil & Gas Journal", url: "https://www.ogj.com/rss", category: "finance", defaultSeverity: "low", region: "global" },

  // ── Natural Disasters Expansion (15) ───────────────────────────────
  { name: "EMSC Earthquakes Europe", url: "https://www.emsc-csem.org/service/rss/rss.php?type=latest", category: "natural", defaultSeverity: "high", region: "europe" },
  { name: "Pacific Tsunami Warning", url: "https://ptwc.weather.gov/ptwc/feeds/ptwc_rss_pacific.xml", category: "natural", defaultSeverity: "critical", region: "global" },
  { name: "NOAA Hurricane Center", url: "https://www.nhc.noaa.gov/index-at.xml", category: "natural", defaultSeverity: "high", region: "global" },
  { name: "JAXA Disasters", url: "https://earth.jaxa.jp/en/feed/", category: "natural", defaultSeverity: "medium", region: "asia" },
  { name: "Copernicus EMS", url: "https://emergency.copernicus.eu/mapping/feed/activations/rss", category: "natural", defaultSeverity: "high", region: "europe" },
  { name: "NIFC Wildfire US", url: "https://www.nifc.gov/rss/incidentInformation.xml", category: "natural", defaultSeverity: "medium", region: "us" },
  { name: "Bureau of Meteorology AU", url: "http://www.bom.gov.au/fwo/IDZ00061.warnings_land_nsw.xml", category: "natural", defaultSeverity: "medium", region: "asia" },
  { name: "Floodlist", url: "https://floodlist.com/feed", category: "natural", defaultSeverity: "medium", region: "global" },
  { name: "Drought Monitor US", url: "https://droughtmonitor.unl.edu/rss/", category: "natural", defaultSeverity: "medium", region: "us" },
  { name: "AFAD Turkey", url: "https://www.afad.gov.tr/rss", category: "natural", defaultSeverity: "high", language: "tr", region: "turkey" },
  { name: "JMA Japan", url: "https://www.jma.go.jp/jma/en/Activities/rss/rss.xml", category: "natural", defaultSeverity: "high", region: "asia" },
  { name: "KNMI Netherlands", url: "https://www.knmi.nl/feeds/rss/news.xml", category: "natural", defaultSeverity: "medium", region: "europe" },
  { name: "MeteoAlarm Europe", url: "https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-europe", category: "natural", defaultSeverity: "medium", region: "europe" },
  { name: "INPE Brazil Space Weather", url: "https://www.inpe.br/rss/", category: "natural", defaultSeverity: "medium", region: "latam" },
  { name: "GeoNet NZ Quakes", url: "https://api.geonet.org.nz/quake?MMI=3", category: "natural", defaultSeverity: "high", region: "asia" },

  // ── Energy Expansion (15) ──────────────────────────────────────────
  { name: "EIA US Energy", url: "https://www.eia.gov/rss/todayinenergy.xml", category: "energy", defaultSeverity: "low", region: "us" },
  { name: "IEA News", url: "https://www.iea.org/rss/news.xml", category: "energy", defaultSeverity: "medium", region: "global" },
  { name: "OPEC News", url: "https://www.opec.org/opec_web/en/press_room/rss.xml", category: "energy", defaultSeverity: "medium", region: "global" },
  { name: "Utility Dive", url: "https://www.utilitydive.com/feeds/news/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Power Technology", url: "https://www.power-technology.com/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "PV Magazine Solar", url: "https://www.pv-magazine.com/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Windpower Monthly", url: "https://www.windpowermonthly.com/rss", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "CleanTechnica", url: "https://cleantechnica.com/feed/", category: "energy", defaultSeverity: "info", region: "global" },
  { name: "Carbon Brief", url: "https://www.carbonbrief.org/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Nuclear Engineering Intl", url: "https://www.neimagazine.com/rss", category: "energy", defaultSeverity: "medium", region: "global" },
  { name: "Platts Oil", url: "https://www.spglobal.com/commodityinsights/en/rss-feed/natural-gas", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "EPDK Turkey Energy", url: "https://www.epdk.gov.tr/rss", category: "energy", defaultSeverity: "low", language: "tr", region: "turkey" },
  { name: "Energy Monitor", url: "https://www.energymonitor.ai/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Hydrogen Insight", url: "https://www.hydrogeninsight.com/rss", category: "energy", defaultSeverity: "info", region: "global" },
  { name: "Electrek", url: "https://electrek.co/feed/", category: "energy", defaultSeverity: "info", region: "global" },

  // ── Health Expansion (12) ──────────────────────────────────────────
  { name: "WHO Disease Outbreaks", url: "https://www.who.int/feeds/entity/don/en/rss.xml", category: "health", defaultSeverity: "high", region: "global" },
  { name: "PAHO Americas Health", url: "https://www.paho.org/en/rss.xml", category: "health", defaultSeverity: "medium", region: "latam" },
  { name: "BMJ News", url: "https://www.bmj.com/rss/recent.xml", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "Nature Medicine", url: "https://www.nature.com/nm.rss", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "New England J Medicine", url: "https://www.nejm.org/action/showFeed?jc=nejm&type=etoc&feed=rss", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "Medical Xpress", url: "https://medicalxpress.com/rss-feed/", category: "health", defaultSeverity: "low", region: "global" },
  { name: "Outbreak News Today", url: "https://outbreaknewstoday.com/feed/", category: "health", defaultSeverity: "high", region: "global" },
  { name: "Endpoint News", url: "https://endpts.com/feed/", category: "health", defaultSeverity: "low", region: "global" },
  { name: "Biopharma Dive", url: "https://www.biopharmadive.com/feeds/news/", category: "health", defaultSeverity: "low", region: "global" },
  { name: "Global Health Now", url: "https://www.globalhealthnow.org/rss.xml", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "Africa CDC", url: "https://africacdc.org/feed/", category: "health", defaultSeverity: "medium", region: "africa" },
  { name: "Fierce Pharma", url: "https://www.fiercepharma.com/rss/xml", category: "health", defaultSeverity: "low", region: "global" },

  // ── Aviation Expansion (8) ─────────────────────────────────────────
  { name: "Airways Magazine", url: "https://airwaysmag.com/feed/", category: "aviation", defaultSeverity: "info", region: "global" },
  { name: "Aviation Safety Network", url: "https://aviation-safety.net/rss/", category: "aviation", defaultSeverity: "high", region: "global" },
  { name: "Airline Ratings", url: "https://www.airlineratings.com/feed/", category: "aviation", defaultSeverity: "info", region: "global" },
  { name: "IATA News", url: "https://www.iata.org/en/pressroom/rss/", category: "aviation", defaultSeverity: "low", region: "global" },
  { name: "FAA Safety", url: "https://www.faa.gov/rss", category: "aviation", defaultSeverity: "medium", region: "us" },
  { name: "EASA Safety", url: "https://www.easa.europa.eu/en/rss", category: "aviation", defaultSeverity: "medium", region: "europe" },
  { name: "LiveATC Forums", url: "https://forums.liveatc.net/index.php?action=.xml;type=rss", category: "aviation", defaultSeverity: "info", region: "global" },
  { name: "Airport Technology", url: "https://www.airport-technology.com/feed/", category: "aviation", defaultSeverity: "info", region: "global" },

  // ── Diplomacy Expansion (10) ───────────────────────────────────────
  { name: "EU External Action", url: "https://www.eeas.europa.eu/eeas/rss_en", category: "diplomacy", defaultSeverity: "medium", region: "europe" },
  { name: "OSCE News", url: "https://www.osce.org/rss.xml", category: "diplomacy", defaultSeverity: "medium", region: "europe" },
  { name: "African Union", url: "https://au.int/rss.xml", category: "diplomacy", defaultSeverity: "low", region: "africa" },
  { name: "ASEAN News", url: "https://asean.org/feed/", category: "diplomacy", defaultSeverity: "low", region: "asia" },
  { name: "G7 Information Centre", url: "https://www.g7.utoronto.ca/rss/", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "BRICS News", url: "https://infobrics.org/feed/", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "Wilson Center", url: "https://www.wilsoncenter.org/rss.xml", category: "diplomacy", defaultSeverity: "low", region: "global" },
  { name: "Stimson Center", url: "https://www.stimson.org/feed/", category: "diplomacy", defaultSeverity: "low", region: "global" },
  { name: "USIP", url: "https://www.usip.org/rss.xml", category: "diplomacy", defaultSeverity: "low", region: "global" },
  { name: "ICC Intl Criminal Court", url: "https://www.icc-cpi.int/rss", category: "diplomacy", defaultSeverity: "medium", region: "global" },

  // ── Protest & Human Rights Expansion (8) ───────────────────────────
  { name: "Reporters Without Borders", url: "https://rsf.org/en/rss.xml", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "Freedom House", url: "https://freedomhouse.org/rss.xml", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "Transparency International", url: "https://www.transparency.org/en/rss.xml", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "OHCHR", url: "https://www.ohchr.org/en/rss-feeds/news-and-events", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "Committee Protect Journalists", url: "https://cpj.org/feed/", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "EFF", url: "https://www.eff.org/rss/updates.xml", category: "protest", defaultSeverity: "low", region: "global" },
  { name: "Access Now", url: "https://www.accessnow.org/feed/", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "Privacy International", url: "https://privacyinternational.org/rss.xml", category: "protest", defaultSeverity: "low", region: "global" },

  // ═══════════════════════════════════════════════════════════════════
  // EXPANSION WAVE 3 — 190+ additional feeds (target: 500+ total)
  // ═══════════════════════════════════════════════════════════════════

  // ── Turkish Sources (22) ─────────────────────────────────────────
  { name: "NTV Haber", url: "https://www.ntv.com.tr/son-dakika.rss", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "CNN Türk", url: "https://www.cnnturk.com/feed/rss/all/news", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "Habertürk", url: "https://www.haberturk.com/rss", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "Sabah", url: "https://www.sabah.com.tr/rss/anasayfa.xml", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "Sözcü", url: "https://www.sozcu.com.tr/rss/tum-haberler.xml", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "Cumhuriyet", url: "https://www.cumhuriyet.com.tr/rss", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "BirGün", url: "https://www.birgun.net/rss", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "T24", url: "https://t24.com.tr/rss", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "Diken", url: "https://www.diken.com.tr/feed/", category: "conflict", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "BloombergHT", url: "https://www.bloomberght.com/rss", category: "finance", defaultSeverity: "low", language: "tr", region: "turkey" },
  { name: "Dünya Gazetesi", url: "https://www.dunya.com/rss", category: "finance", defaultSeverity: "low", language: "tr", region: "turkey" },
  { name: "Para Analiz", url: "https://www.paraanaliz.com/feed/", category: "finance", defaultSeverity: "low", language: "tr", region: "turkey" },
  { name: "Webrazzi", url: "https://webrazzi.com/feed/", category: "tech", defaultSeverity: "info", language: "tr", region: "turkey" },
  { name: "ShiftDelete", url: "https://shiftdelete.net/feed", category: "tech", defaultSeverity: "info", language: "tr", region: "turkey" },
  { name: "Chip Online TR", url: "https://www.chip.com.tr/rss/anasayfa.xml", category: "tech", defaultSeverity: "info", language: "tr", region: "turkey" },
  { name: "Donanım Haber", url: "https://www.donanimhaber.com/rss/tum/", category: "tech", defaultSeverity: "info", language: "tr", region: "turkey" },
  { name: "TRT World EN", url: "https://www.trtworld.com/rss", category: "conflict", defaultSeverity: "medium", region: "turkey" },
  { name: "Bianet EN", url: "https://bianet.org/english/rss", category: "protest", defaultSeverity: "medium", region: "turkey" },
  { name: "Ahval News", url: "https://ahvalnews.com/rss.xml", category: "diplomacy", defaultSeverity: "medium", region: "turkey" },
  { name: "Sağlık Bakanlığı", url: "https://www.saglik.gov.tr/rss", category: "health", defaultSeverity: "medium", language: "tr", region: "turkey" },
  { name: "Enerji Günlüğü", url: "https://www.enerjigunlugu.net/feed", category: "energy", defaultSeverity: "low", language: "tr", region: "turkey" },
  { name: "Havacılık ve Uzay", url: "https://www.hvk.gov.tr/rss", category: "aviation", defaultSeverity: "info", language: "tr", region: "turkey" },

  // ── Asia-Pacific Expansion (22) ──────────────────────────────────
  { name: "Korea Herald", url: "https://www.koreaherald.com/common/rss_xml.php", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Taiwan News", url: "https://www.taiwannews.com.tw/en/rss", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Taipei Times", url: "https://www.taipeitimes.com/xml/rss.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Mainichi Daily News", url: "https://mainichi.jp/english/rss/etc/mainichi.rss", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "South China Morning Post Asia", url: "https://www.scmp.com/rss/5/feed", category: "diplomacy", defaultSeverity: "medium", region: "asia" },
  { name: "Asia Times", url: "https://asiatimes.com/feed/", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Diplomat ASEAN", url: "https://thediplomat.com/regions/southeast-asia/feed/", category: "diplomacy", defaultSeverity: "low", region: "asia" },
  { name: "Myanmar Now", url: "https://www.myanmar-now.org/en/feed", category: "conflict", defaultSeverity: "high", region: "asia" },
  { name: "Benar News", url: "https://www.benarnews.org/english/rss/news.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "East Asia Forum", url: "https://www.eastasiaforum.org/feed/", category: "diplomacy", defaultSeverity: "low", region: "asia" },
  { name: "India Today", url: "https://www.indiatoday.in/rss/home", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "NDTV India", url: "https://feeds.feedburner.com/ndtvnews-top-stories", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Hindustan Times", url: "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Wire India", url: "https://thewire.in/feed", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Scroll India", url: "https://scroll.in/rss/feed.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Geo News Pakistan", url: "https://www.geo.tv/rss/1/0", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Daily Star Bangladesh", url: "https://www.thedailystar.net/frontpage/rss.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "Nikkei Asia Tech", url: "https://asia.nikkei.com/rss/feed/nar?category=Technology", category: "tech", defaultSeverity: "info", region: "asia" },
  { name: "KrASIA", url: "https://kr-asia.com/feed", category: "tech", defaultSeverity: "info", region: "asia" },
  { name: "Tech in Asia", url: "https://www.techinasia.com/feed", category: "tech", defaultSeverity: "info", region: "asia" },
  { name: "ABC Australia", url: "https://www.abc.net.au/news/feed/2942460/rss.xml", category: "conflict", defaultSeverity: "medium", region: "asia" },
  { name: "New Zealand Herald", url: "https://www.nzherald.co.nz/arc/outboundfeeds/rss/curated/78/", category: "conflict", defaultSeverity: "medium", region: "asia" },

  // ── Africa Expansion (16) ────────────────────────────────────────
  { name: "AllAfrica", url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Africa Report", url: "https://www.theafricareport.com/feed/", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Daily Maverick", url: "https://www.dailymaverick.co.za/feed/", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "TechCabal", url: "https://techcabal.com/feed/", category: "tech", defaultSeverity: "info", region: "africa" },
  { name: "ISS Africa", url: "https://issafrica.org/feed", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Punch Nigeria", url: "https://punchng.com/feed/", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Premium Times Nigeria", url: "https://www.premiumtimesng.com/feed", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "The East African", url: "https://www.theeastafrican.co.ke/tea/rss", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "Business Day SA", url: "https://www.businesslive.co.za/bd/rss/", category: "finance", defaultSeverity: "low", region: "africa" },
  { name: "Quartz Africa", url: "https://qz.com/africa/feed/", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "African Arguments", url: "https://africanarguments.org/feed/", category: "diplomacy", defaultSeverity: "low", region: "africa" },
  { name: "Disrupt Africa", url: "https://disrupt-africa.com/feed/", category: "tech", defaultSeverity: "info", region: "africa" },
  { name: "TechPoint Africa", url: "https://techpoint.africa/feed/", category: "tech", defaultSeverity: "info", region: "africa" },
  { name: "Sudan Tribune", url: "https://sudantribune.com/feed/", category: "conflict", defaultSeverity: "high", region: "africa" },
  { name: "Ethiopian Reporter", url: "https://www.thereporterethiopia.com/feed/", category: "conflict", defaultSeverity: "medium", region: "africa" },
  { name: "IOL South Africa", url: "https://www.iol.co.za/cmlink/1.640", category: "conflict", defaultSeverity: "medium", region: "africa" },

  // ── Latin America Expansion (12) ─────────────────────────────────
  { name: "Americas Quarterly", url: "https://americasquarterly.org/feed/", category: "diplomacy", defaultSeverity: "low", region: "latam" },
  { name: "MercoPress", url: "https://en.mercopress.com/rss", category: "conflict", defaultSeverity: "medium", region: "latam" },
  { name: "Mongabay Latam EN", url: "https://news.mongabay.com/feed/", category: "natural", defaultSeverity: "medium", region: "latam" },
  { name: "Brazil Wire", url: "https://www.brasilwire.com/feed/", category: "conflict", defaultSeverity: "medium", region: "latam" },
  { name: "Tico Times Costa Rica", url: "https://ticotimes.net/feed", category: "conflict", defaultSeverity: "medium", region: "latam" },
  { name: "Latin Finance", url: "https://www.latinfinance.com/rss", category: "finance", defaultSeverity: "low", region: "latam" },
  { name: "Diálogo Americas", url: "https://dialogo-americas.com/feed/", category: "conflict", defaultSeverity: "medium", region: "latam" },
  { name: "NACLA", url: "https://nacla.org/feed", category: "diplomacy", defaultSeverity: "low", region: "latam" },
  { name: "Peru Reports", url: "https://perureports.com/feed/", category: "conflict", defaultSeverity: "medium", region: "latam" },
  { name: "InsightCrime", url: "https://insightcrime.org/feed/", category: "conflict", defaultSeverity: "high", region: "latam" },
  { name: "BNamericas", url: "https://www.bnamericas.com/en/rss", category: "finance", defaultSeverity: "low", region: "latam" },
  { name: "TeleSUR English", url: "https://www.telesurenglish.net/rss/news.xml", category: "conflict", defaultSeverity: "medium", region: "latam" },

  // ── Middle East Expansion (13) ───────────────────────────────────
  { name: "Arab News", url: "https://www.arabnews.com/rss.xml", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "Gulf News", url: "https://gulfnews.com/rss", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "Al-Monitor", url: "https://www.al-monitor.com/rss", category: "diplomacy", defaultSeverity: "medium", region: "middleeast" },
  { name: "Haaretz", url: "https://www.haaretz.com/cmlink/1.628752", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "Jerusalem Post", url: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "Daily Star Lebanon", url: "https://www.dailystar.com.lb/RSS.aspx", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "MEE Opinion", url: "https://www.middleeasteye.net/opinion/rss", category: "diplomacy", defaultSeverity: "low", region: "middleeast" },
  { name: "Asharq Al-Awsat", url: "https://english.aawsat.com/feed", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "i24 News", url: "https://www.i24news.tv/en/rss", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "Rudaw Kurdistan", url: "https://www.rudaw.net/english/rss", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "Press TV Iran", url: "https://www.presstv.ir/RSS", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "Khaleej Times", url: "https://www.khaleejtimes.com/rss", category: "conflict", defaultSeverity: "medium", region: "middleeast" },
  { name: "MEMO Middle East Monitor", url: "https://www.middleeastmonitor.com/feed/", category: "conflict", defaultSeverity: "medium", region: "middleeast" },

  // ── Specialized Tech Expansion (22) ──────────────────────────────
  { name: "Lobsters", url: "https://lobste.rs/rss", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Slashdot", url: "https://rss.slashdot.org/Slashdot/slashdotMain", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "The Register", url: "https://www.theregister.com/headlines.atom", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "InfoQ", url: "https://feed.infoq.com/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Stratechery", url: "https://stratechery.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Benedict Evans", url: "https://www.ben-evans.com/feed", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Changelog", url: "https://changelog.com/feed", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Hackaday", url: "https://hackaday.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "TechRadar", url: "https://www.techradar.com/rss", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "CNET", url: "https://www.cnet.com/rss/news/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Turing Post AI", url: "https://www.turingpost.com/feed", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Import AI", url: "https://importai.substack.com/feed", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Last Week in AI", url: "https://lastweekin.ai/feed", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "SiliconANGLE", url: "https://siliconangle.com/feed/", category: "tech", defaultSeverity: "info", region: "global" },
  { name: "Dark Reading Cloud", url: "https://www.darkreading.com/rss/cloud-security.xml", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "SecurityWeek ICS", url: "https://www.securityweek.com/category/ics-ot/feed/", category: "cyber", defaultSeverity: "high", region: "global" },
  { name: "Help Net Security", url: "https://www.helpnetsecurity.com/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Naked Security", url: "https://news.sophos.com/en-us/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Risky Business", url: "https://risky.biz/feeds/risky-business/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "GBHackers Security", url: "https://gbhackers.com/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Cyber Defense Magazine", url: "https://www.cyberdefensemagazine.com/feed/", category: "cyber", defaultSeverity: "medium", region: "global" },
  { name: "Security Affairs", url: "https://securityaffairs.com/feed", category: "cyber", defaultSeverity: "medium", region: "global" },

  // ── Specialized Finance Expansion (20) ───────────────────────────
  { name: "World Bank Blog", url: "https://blogs.worldbank.org/feed", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "IMF Blog", url: "https://www.imf.org/en/Blogs/rss", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "BIS Speeches", url: "https://www.bis.org/doclist/cbspeeches.rss", category: "finance", defaultSeverity: "medium", region: "global" },
  { name: "OECD Economy", url: "https://www.oecd.org/economy/rss/", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "WTO News", url: "https://www.wto.org/english/news_e/news_e.rss", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Bruegel", url: "https://www.bruegel.org/rss.xml", category: "finance", defaultSeverity: "low", region: "europe" },
  { name: "Peterson Institute", url: "https://www.piie.com/rss.xml", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Money Control India", url: "https://www.moneycontrol.com/rss/latestnews.xml", category: "finance", defaultSeverity: "low", region: "asia" },
  { name: "Economic Times India", url: "https://economictimes.indiatimes.com/rssfeedstopstories.cms", category: "finance", defaultSeverity: "low", region: "asia" },
  { name: "Caixin Global", url: "https://www.caixinglobal.com/rss.html", category: "finance", defaultSeverity: "medium", region: "asia" },
  { name: "Reuters Bonds", url: "https://feeds.reuters.com/reuters/bondsNews", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Reuters Commodities", url: "https://feeds.reuters.com/reuters/commoditiesNews", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Institutional Investor", url: "https://www.institutionalinvestor.com/rss/", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Risk.net", url: "https://www.risk.net/feeds/rss", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Central Banking", url: "https://www.centralbanking.com/rss", category: "finance", defaultSeverity: "medium", region: "global" },
  { name: "Econbrowser", url: "https://econbrowser.com/feed", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Calculated Risk", url: "https://www.calculatedriskblog.com/feeds/posts/default?alt=rss", category: "finance", defaultSeverity: "low", region: "us" },
  { name: "Wolf Street", url: "https://wolfstreet.com/feed/", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Finextra", url: "https://www.finextra.com/rss/headlines.aspx", category: "finance", defaultSeverity: "low", region: "global" },
  { name: "Benzinga", url: "https://www.benzinga.com/feed", category: "finance", defaultSeverity: "low", region: "us" },

  // ── Health & Science Expansion (13) ──────────────────────────────
  { name: "Science Daily Health", url: "https://www.sciencedaily.com/rss/health_medicine.xml", category: "health", defaultSeverity: "low", region: "global" },
  { name: "NIH News", url: "https://www.nih.gov/news-events/news-releases/feed", category: "health", defaultSeverity: "medium", region: "us" },
  { name: "EMA European Medicines", url: "https://www.ema.europa.eu/en/rss/press-releases.xml", category: "health", defaultSeverity: "medium", region: "europe" },
  { name: "Science Magazine", url: "https://www.science.org/rss/news_current.xml", category: "health", defaultSeverity: "low", region: "global" },
  { name: "Nature News", url: "https://www.nature.com/nature.rss", category: "health", defaultSeverity: "low", region: "global" },
  { name: "Contagion Live", url: "https://www.contagionlive.com/rss", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "Precision Vax", url: "https://www.precisionvaccinations.com/rss.xml", category: "health", defaultSeverity: "low", region: "global" },
  { name: "FDA News", url: "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml", category: "health", defaultSeverity: "medium", region: "us" },
  { name: "Health Policy Watch", url: "https://healthpolicy-watch.news/feed/", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "GAVI Vaccine Alliance", url: "https://www.gavi.org/rss.xml", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "Devex Global Health", url: "https://www.devex.com/news/rss", category: "health", defaultSeverity: "low", region: "global" },
  { name: "MSF Field News", url: "https://www.msf.org/rss/all", category: "health", defaultSeverity: "medium", region: "global" },
  { name: "JAMA Network", url: "https://jamanetwork.com/rss/site_3/67.xml", category: "health", defaultSeverity: "medium", region: "global" },

  // ── Energy & Climate Expansion (13) ──────────────────────────────
  { name: "Greentech Media", url: "https://www.greentechmedia.com/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "E&E News", url: "https://www.eenews.net/feed/", category: "energy", defaultSeverity: "low", region: "us" },
  { name: "Energy Voice", url: "https://www.energyvoice.com/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Recharge News", url: "https://www.rechargenews.com/rss", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Climate Home News", url: "https://www.climatechangenews.com/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Inside Climate News", url: "https://insideclimatenews.org/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Carbon Tracker", url: "https://carbontracker.org/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Global Energy Monitor", url: "https://globalenergymonitor.org/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Energy Transition", url: "https://energytransition.org/feed/", category: "energy", defaultSeverity: "info", region: "global" },
  { name: "Upstream Online Oil", url: "https://www.upstreamonline.com/rss", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Bloomberg Green", url: "https://www.bloomberg.com/green/feed/", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "IRENA News", url: "https://www.irena.org/rss", category: "energy", defaultSeverity: "low", region: "global" },
  { name: "Nuclear Threat Initiative", url: "https://www.nti.org/rss/all/", category: "energy", defaultSeverity: "high", region: "global" },

  // ── Aviation & Maritime Expansion (11) ───────────────────────────
  { name: "Aviation Week", url: "https://aviationweek.com/rss.xml", category: "aviation", defaultSeverity: "low", region: "global" },
  { name: "AeroTime Hub", url: "https://www.aerotime.aero/feed", category: "aviation", defaultSeverity: "info", region: "global" },
  { name: "Paddle Your Own Kanoo Aviation", url: "https://www.paddleyourownkanoo.com/feed/", category: "aviation", defaultSeverity: "info", region: "global" },
  { name: "One Mile at a Time", url: "https://onemileatatime.com/feed/", category: "aviation", defaultSeverity: "info", region: "global" },
  { name: "Splash 247 Maritime", url: "https://splash247.com/category/sector/tanker/feed/", category: "aviation", defaultSeverity: "low", region: "global" },
  { name: "Maritime Executive", url: "https://maritime-executive.com/feed", category: "aviation", defaultSeverity: "low", region: "global" },
  { name: "Lloyd's List", url: "https://lloydslist.maritimeintelligence.informa.com/rss/", category: "aviation", defaultSeverity: "low", region: "global" },
  { name: "TradeWinds Shipping", url: "https://www.tradewindsnews.com/rss", category: "aviation", defaultSeverity: "low", region: "global" },
  { name: "FlightRadar24 Blog", url: "https://www.flightradar24.com/blog/feed/", category: "aviation", defaultSeverity: "info", region: "global" },
  { name: "Seatrade Maritime", url: "https://www.seatrade-maritime.com/rss.xml", category: "aviation", defaultSeverity: "low", region: "global" },
  { name: "Offshore Engineer", url: "https://www.oedigital.com/rss", category: "aviation", defaultSeverity: "low", region: "global" },

  // ── Diplomacy & Think Tanks Expansion (10) ───────────────────────
  { name: "Lowy Institute", url: "https://www.lowyinstitute.org/rss.xml", category: "diplomacy", defaultSeverity: "low", region: "asia" },
  { name: "RUSI", url: "https://www.rusi.org/rss.xml", category: "diplomacy", defaultSeverity: "medium", region: "europe" },
  { name: "German Marshall Fund", url: "https://www.gmfus.org/feed", category: "diplomacy", defaultSeverity: "low", region: "global" },
  { name: "European Policy Centre", url: "https://www.epc.eu/en/rss", category: "diplomacy", defaultSeverity: "low", region: "europe" },
  { name: "ECFR", url: "https://ecfr.eu/feed/", category: "diplomacy", defaultSeverity: "medium", region: "europe" },
  { name: "Observer Research Foundation", url: "https://www.orfonline.org/feed", category: "diplomacy", defaultSeverity: "low", region: "asia" },
  { name: "IISS Shangri-La", url: "https://www.iiss.org/blogs/analysis/feed/", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "War on the Rocks Briefs", url: "https://warontherocks.com/category/briefs/feed/", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "Eurasia Group", url: "https://www.eurasiagroup.net/rss", category: "diplomacy", defaultSeverity: "medium", region: "global" },
  { name: "Geopolitical Futures", url: "https://geopoliticalfutures.com/feed/", category: "diplomacy", defaultSeverity: "medium", region: "global" },

  // ── Protest & Civil Society Expansion (6) ────────────────────────
  { name: "Global Voices", url: "https://globalvoices.org/feed/", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "CIVICUS Monitor", url: "https://monitor.civicus.org/feed/", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "Article 19", url: "https://www.article19.org/feed/", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "Front Line Defenders", url: "https://www.frontlinedefenders.org/en/rss.xml", category: "protest", defaultSeverity: "high", region: "global" },
  { name: "WITNESS Media Lab", url: "https://lab.witness.org/feed/", category: "protest", defaultSeverity: "medium", region: "global" },
  { name: "OpenDemocracy", url: "https://www.opendemocracy.net/en/rss/", category: "protest", defaultSeverity: "low", region: "global" },

  // ── Natural Disasters Expansion (10) ─────────────────────────────
  { name: "ITIC Tsunami", url: "https://www.tsunamiwave.info/rss.xml", category: "natural", defaultSeverity: "critical", region: "global" },
  { name: "FEMA US", url: "https://www.fema.gov/feeds/disasters/feed.xml", category: "natural", defaultSeverity: "high", region: "us" },
  { name: "PHIVOLCS Philippines", url: "https://www.phivolcs.dost.gov.ph/rss", category: "natural", defaultSeverity: "high", region: "asia" },
  { name: "INGV Italy Earthquakes", url: "https://www.ingv.it/feed", category: "natural", defaultSeverity: "high", region: "europe" },
  { name: "WMO World Meteorological", url: "https://public.wmo.int/en/rss.xml", category: "natural", defaultSeverity: "medium", region: "global" },
  { name: "UNDRR", url: "https://www.undrr.org/rss.xml", category: "natural", defaultSeverity: "medium", region: "global" },
  { name: "Earth Observatory NASA", url: "https://earthobservatory.nasa.gov/feeds/earth-observatory.rss", category: "natural", defaultSeverity: "medium", region: "global" },
  { name: "Fire Information (NASA FIRMS)", url: "https://firms.modaps.eosdis.nasa.gov/rss/", category: "natural", defaultSeverity: "medium", region: "global" },
  { name: "EFAS European Floods", url: "https://www.efas.eu/rss.xml", category: "natural", defaultSeverity: "medium", region: "europe" },
  { name: "Severe Weather Europe", url: "https://www.severe-weather.eu/feed/", category: "natural", defaultSeverity: "medium", region: "europe" },
];

export const FEED_COUNT = SEED_FEEDS.length;
