/**
 * OSINT Resource Directory — seed data.
 *
 * Sourced from awesome-osint (github.com/azaduluyazi/awesome-osint) and
 * curated for news-aggregator relevance. The full list is ~1000 items;
 * this seed keeps the ~100 most useful for WorldScope's audience.
 *
 * Seed flow: this file → admin/seed-osint endpoint → Supabase
 * `osint_resources` table → read at runtime by /osint page.
 *
 * Three integration types:
 *   feed    — we ingest it server-side (listed here for UI visibility)
 *   widget  — iframe on /osint/live-maps (Gaia+ tier)
 *   link    — external directory entry (free tier)
 */

export type OsintIntegrationType = "feed" | "widget" | "link";

export type OsintCategory =
  | "conflict"
  | "cyber"
  | "geospatial"
  | "satellite"
  | "social"
  | "telegram"
  | "news"
  | "fact-check"
  | "domain-ip"
  | "vuln"
  | "weather"
  | "data"
  | "other";

export type OsintScope = "GLOBAL" | "REGION" | "COUNTRY" | "CITY";
export type OsintCost = "free" | "freemium" | "paid";
export type OsintTier = "free" | "global" | "enterprise";

export interface OsintResource {
  slug: string;
  name: string;
  url: string;
  description: string;
  descriptionTr?: string;
  integrationType: OsintIntegrationType;
  category: OsintCategory;
  scope: OsintScope;
  region?: string;
  countryCode?: string; // ISO 3166-1 alpha-2
  city?: string;
  cost: OsintCost;
  requiredTier: OsintTier;
  embedUrl?: string;
  embedHeight?: number;
  tags: string[];
  priority: number;
}

export const SEED_OSINT_RESOURCES: OsintResource[] = [
  // ═══════════════════════════════════════════════════════════════════
  // TYPE B — Embeddable widgets (Gaia+ tier)
  // ═══════════════════════════════════════════════════════════════════
  {
    slug: "kaspersky-cybermap",
    name: "Kaspersky Cyberthreat Map",
    url: "https://cybermap.kaspersky.com/",
    embedUrl: "https://cybermap.kaspersky.com/en/widget/dynamic/dark",
    description: "Real-time global cyberattack visualisation.",
    descriptionTr: "Canlı global siber saldırı haritası.",
    integrationType: "widget",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "global",
    embedHeight: 700,
    tags: ["threat-map", "realtime", "ddos"],
    priority: 100,
  },
  {
    slug: "bitdefender-threatmap",
    name: "Bitdefender Threat Map",
    url: "https://threatmap.bitdefender.com/",
    embedUrl: "https://threatmap.bitdefender.com/",
    description: "Live map of cyberattacks, infections, and spam.",
    descriptionTr: "Canlı siber saldırı, enfeksiyon ve spam haritası.",
    integrationType: "widget",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "global",
    embedHeight: 700,
    tags: ["threat-map", "realtime"],
    priority: 95,
  },
  {
    slug: "checkpoint-threatmap",
    name: "Check Point Live Cyber Threat Map",
    url: "https://threatmap.checkpoint.com/",
    description: "Live cyberattack telemetry by Check Point ThreatCloud. (Embed blocked by X-Frame-Options.)",
    descriptionTr: "Check Point ThreatCloud canlı saldırı haritası. (Embed X-Frame-Options ile engelli.)",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["threat-map", "realtime"],
    priority: 90,
  },
  {
    slug: "fortiguard-threatmap",
    name: "Fortiguard Threat Map",
    url: "https://fortiguard.fortinet.com/threat-map",
    embedUrl: "https://fortiguard.fortinet.com/threat-map",
    description: "Fortinet's live cyber threat visualization.",
    descriptionTr: "Fortinet canlı siber tehdit görselleştirmesi.",
    integrationType: "widget",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "global",
    embedHeight: 700,
    tags: ["threat-map", "realtime"],
    priority: 85,
  },
  {
    slug: "radware-threatmap",
    name: "Radware Live Threat Map",
    url: "https://livethreatmap.radware.com/",
    embedUrl: "https://livethreatmap.radware.com/",
    description: "Radware DDoS and cyber attack live map.",
    descriptionTr: "Radware DDoS ve siber saldırı canlı haritası.",
    integrationType: "widget",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "global",
    embedHeight: 700,
    tags: ["threat-map", "ddos"],
    priority: 80,
  },
  {
    slug: "imperva-threatmap",
    name: "Imperva Live Threat Map",
    url: "https://www.imperva.com/cyber-threat-attack-map/",
    description: "Application-layer attack visualization. (Embed blocked by X-Frame-Options: SAMEORIGIN.)",
    descriptionTr: "Uygulama-katmanı saldırı görselleştirmesi. (Embed engelli.)",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["threat-map", "waf"],
    priority: 75,
  },
  {
    slug: "netscout-horizon",
    name: "NETSCOUT Cyber Threat Horizon",
    url: "https://horizon.netscout.com/",
    description: "DDoS attack telemetry across global ISPs. (Embed blocked by X-Frame-Options.)",
    descriptionTr: "Global ISP'ler üzerinden DDoS telemetrisi. (Embed engelli.)",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["threat-map", "ddos"],
    priority: 70,
  },
  {
    slug: "zscaler-threatmap",
    name: "Zscaler ThreatLabz Map",
    url: "https://threatlabz.zscaler.com/cloud-insights/threat-map-dashboard",
    embedUrl: "https://threatlabz.zscaler.com/cloud-insights/threat-map-dashboard",
    description: "Zero trust platform threat telemetry.",
    descriptionTr: "Zero trust platformu tehdit telemetrisi.",
    integrationType: "widget",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "global",
    embedHeight: 700,
    tags: ["threat-map"],
    priority: 65,
  },
  {
    slug: "ibm-xforce-activity",
    name: "IBM X-Force Activity Map",
    url: "https://exchange.xforce.ibmcloud.com/activity/map",
    description: "IBM threat intelligence activity feed map. (Embed blocked by X-Frame-Options: SAMEORIGIN.)",
    descriptionTr: "IBM tehdit istihbaratı aktivite haritası. (Embed engelli.)",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["threat-map", "xforce"],
    priority: 60,
  },
  {
    slug: "windy-weather",
    name: "Windy.com Weather Map",
    url: "https://www.windy.com/",
    embedUrl: "https://embed.windy.com/embed2.html?type=map&location=coordinates&metricRain=mm&metricTemp=°C&metricWind=km/h&zoom=3",
    description: "Hurricane, storm, and precipitation tracker.",
    descriptionTr: "Kasırga, fırtına ve yağış takibi.",
    integrationType: "widget",
    category: "weather",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "global",
    embedHeight: 700,
    tags: ["weather", "realtime", "storm"],
    priority: 90,
  },
  {
    slug: "zoom-earth",
    name: "Zoom Earth — Live Storms",
    url: "https://zoom.earth/",
    description: "Live satellite imagery, hurricanes, and wildfires. (Embed blocked by X-Frame-Options: SAMEORIGIN.)",
    descriptionTr: "Canlı uydu görüntüsü, kasırga ve orman yangınları. (Embed engelli.)",
    integrationType: "link",
    category: "satellite",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["satellite", "storm", "wildfire"],
    priority: 85,
  },
  {
    slug: "liveuamap",
    name: "Liveuamap",
    url: "https://liveuamap.com/",
    embedUrl: "https://liveuamap.com/",
    description: "Real-time conflict markers on a global map.",
    descriptionTr: "Global harita üzerinde canlı çatışma işaretleri.",
    integrationType: "widget",
    category: "conflict",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "global",
    embedHeight: 800,
    tags: ["conflict", "realtime", "war"],
    priority: 100,
  },
  {
    slug: "suncalc",
    name: "SunCalc",
    url: "https://www.suncalc.org/",
    embedUrl: "https://www.suncalc.org/",
    description: "Sun position and shadow calculator (geolocation tool).",
    descriptionTr: "Güneş konumu ve gölge hesaplayıcı.",
    integrationType: "widget",
    category: "geospatial",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "global",
    embedHeight: 600,
    tags: ["geolocation", "verification"],
    priority: 40,
  },
  {
    slug: "satellites-pro",
    name: "Satellites Pro",
    url: "https://satellites.pro/",
    description: "High-resolution satellite imagery viewer. (Embed blocked by X-Frame-Options: SAMEORIGIN.)",
    descriptionTr: "Yüksek çözünürlüklü uydu görüntü izleyici. (Embed engelli.)",
    integrationType: "link",
    category: "satellite",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["satellite", "imagery"],
    priority: 70,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TYPE A — Automated data sources (marked visible in directory too)
  // These are also added to SEED_FEEDS for ingestion; here they're
  // surfaced in /osint so users see what feeds our convergence engine.
  // ═══════════════════════════════════════════════════════════════════
  {
    slug: "urlhaus-abuse-ch",
    name: "URLhaus (abuse.ch)",
    url: "https://urlhaus.abuse.ch/",
    description: "Malware URL feed, CSV/JSON. Ingested into our convergence layer.",
    descriptionTr: "Zararlı URL beslemesi. Konverjans katmanına ingest edilir.",
    integrationType: "feed",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["malware", "ioc", "threat-intel"],
    priority: 80,
  },
  {
    slug: "bgp-tools",
    name: "BGP.tools",
    url: "https://bgp.tools/",
    description: "BGP prefix + AS path data. Outage and route-leak signals.",
    descriptionTr: "BGP prefix + AS path verisi. İnternet kesintisi sinyali.",
    integrationType: "feed",
    category: "cyber",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["bgp", "outage", "network"],
    priority: 85,
  },
  {
    slug: "shodan",
    name: "Shodan",
    url: "https://www.shodan.io/",
    description: "Search engine for internet-connected devices.",
    descriptionTr: "İnternete bağlı cihazlar için arama motoru.",
    integrationType: "feed",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["scanning", "iot", "infrastructure"],
    priority: 90,
  },
  {
    slug: "censys",
    name: "Censys",
    url: "https://search.censys.io/",
    description: "Internet-wide scan data, cert transparency, host changes.",
    descriptionTr: "İnternet çapında tarama verisi, sertifika şeffaflığı.",
    integrationType: "feed",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["scanning", "certificates"],
    priority: 80,
  },
  {
    slug: "greynoise",
    name: "GreyNoise",
    url: "https://viz.greynoise.io/",
    description: "Context for mass-scanning IPs, early-warning signal.",
    descriptionTr: "Toplu tarama IP'leri için bağlam, erken uyarı sinyali.",
    integrationType: "feed",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["ip-reputation", "early-warning"],
    priority: 75,
  },
  {
    slug: "virustotal",
    name: "VirusTotal",
    url: "https://www.virustotal.com/",
    description: "File and URL reputation by multi-engine scan.",
    descriptionTr: "Çoklu-motor taramayla dosya ve URL itibarı.",
    integrationType: "feed",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["malware", "ioc"],
    priority: 85,
  },
  {
    slug: "securitytrails",
    name: "SecurityTrails",
    url: "https://securitytrails.com/dns-trails",
    description: "Historical DNS and WHOIS data for entity enrichment.",
    descriptionTr: "Tarihsel DNS ve WHOIS verisi, entity zenginleştirme.",
    integrationType: "feed",
    category: "domain-ip",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["dns", "whois", "history"],
    priority: 70,
  },
  {
    slug: "sentinel-hub",
    name: "Sentinel Hub",
    url: "https://www.sentinel-hub.com/",
    description: "Copernicus satellite imagery API for event verification.",
    descriptionTr: "Copernicus uydu görüntüsü API'si, olay doğrulama için.",
    integrationType: "feed",
    category: "satellite",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["satellite", "verification"],
    priority: 75,
  },
  {
    slug: "usgs-earthexplorer",
    name: "USGS EarthExplorer",
    url: "https://earthexplorer.usgs.gov/",
    description: "USGS satellite and aerial imagery archive.",
    descriptionTr: "USGS uydu ve hava görüntü arşivi.",
    integrationType: "feed",
    category: "satellite",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["satellite", "archive"],
    priority: 60,
  },
  {
    slug: "geonames",
    name: "GeoNames",
    url: "http://www.geonames.org/",
    description: "Global place-name database, used for event geocoding.",
    descriptionTr: "Global yer-adı veritabanı, olay geocoding için.",
    integrationType: "feed",
    category: "geospatial",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["geocoding", "reference"],
    priority: 55,
  },
  {
    slug: "dbpedia",
    name: "DBPedia",
    url: "https://wiki.dbpedia.org/",
    description: "Structured Wikipedia data via SPARQL, entity linking.",
    descriptionTr: "SPARQL üzerinden yapılandırılmış Wikipedia verisi.",
    integrationType: "feed",
    category: "data",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["linked-data", "entity"],
    priority: 50,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TYPE C — External directory links (free tier, high SEO value)
  // ═══════════════════════════════════════════════════════════════════

  // ── Conflict & Intelligence ──
  {
    slug: "intelligence-x",
    name: "Intelligence X",
    url: "https://intelx.io/tools",
    description: "Search dark web, leaks, and public data sources.",
    descriptionTr: "Dark web, sızıntı ve açık kaynaklarda arama.",
    integrationType: "link",
    category: "domain-ip",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["leaks", "dark-web", "search"],
    priority: 95,
  },
  {
    slug: "gdelt-project",
    name: "GDELT Project",
    url: "https://www.gdeltproject.org/",
    description: "Global event database updated every 15 minutes.",
    descriptionTr: "15 dakikada bir güncellenen global olay veritabanı.",
    integrationType: "link",
    category: "conflict",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["events", "database", "research"],
    priority: 100,
  },
  {
    slug: "silobreaker",
    name: "Silobreaker",
    url: "https://www.silobreaker.com/",
    description: "Threat intelligence news API with topic and entity graphs.",
    descriptionTr: "Konu ve entity grafikli tehdit istihbarat API'si.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "paid",
    requiredTier: "free",
    tags: ["threat-intel", "api"],
    priority: 65,
  },
  {
    slug: "storyful",
    name: "Storyful",
    url: "https://storyful.com/",
    description: "Verified social-news service for breaking events.",
    descriptionTr: "Gelişen olaylar için doğrulanmış sosyal haber servisi.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "paid",
    requiredTier: "free",
    tags: ["verification", "social-news"],
    priority: 60,
  },

  // ── Newspaper/News directories ──
  {
    slug: "abyz-news-links",
    name: "ABYZ News Links",
    url: "https://www.abyznewslinks.com/",
    description: "Directory of online news sources by country.",
    descriptionTr: "Ülkeye göre online haber kaynakları dizini.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["directory", "by-country"],
    priority: 70,
  },
  {
    slug: "newspaper-map",
    name: "Newspaper Map",
    url: "https://newspapermap.com/",
    description: "Interactive world map of newspapers.",
    descriptionTr: "Gazetelerin interaktif dünya haritası.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["directory", "map"],
    priority: 55,
  },
  {
    slug: "online-newspapers",
    name: "OnlineNewspapers",
    url: "https://www.onlinenewspapers.com/",
    description: "Global directory of online newspapers.",
    descriptionTr: "Online gazetelerin global dizini.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["directory"],
    priority: 50,
  },
  {
    slug: "world-newspapers",
    name: "World-Newspapers",
    url: "https://www.world-newspapers.com/",
    description: "World newspapers and magazines by country and language.",
    descriptionTr: "Ülke ve dile göre dünya gazete ve dergileri.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["directory", "by-country"],
    priority: 45,
  },
  {
    slug: "flipboard",
    name: "Flipboard",
    url: "https://flipboard.com/",
    description: "Topic-based news aggregator with curated magazines.",
    descriptionTr: "Konu bazlı haber aggregator'ı.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["aggregator"],
    priority: 30,
  },
  {
    slug: "newsmap-jp",
    name: "Newsmap.jp",
    url: "https://newsmap.jp/",
    description: "Treemap visualisation of Google News.",
    descriptionTr: "Google News'in treemap görselleştirmesi.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["visualization"],
    priority: 55,
  },
  {
    slug: "emergent-info",
    name: "Emergent.info",
    url: "https://www.emergent.info/",
    description: "Tracks rumors and misinformation on breaking events.",
    descriptionTr: "Gelişen olaylarda söylenti ve yanlış bilgi takibi.",
    integrationType: "link",
    category: "fact-check",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["rumors", "verification"],
    priority: 45,
  },

  // ── Fact-check ──
  {
    slug: "snopes",
    name: "Snopes",
    url: "https://www.snopes.com/",
    description: "Fact-checking urban legends and breaking claims.",
    descriptionTr: "Söylenti ve gelişen iddia fact-checking'i.",
    integrationType: "link",
    category: "fact-check",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["fact-check"],
    priority: 60,
  },
  {
    slug: "factcheck-org",
    name: "FactCheck.org",
    url: "https://www.factcheck.org/",
    description: "Annenberg Public Policy Center fact-checking.",
    descriptionTr: "Annenberg Public Policy fact-checking.",
    integrationType: "link",
    category: "fact-check",
    scope: "COUNTRY",
    countryCode: "US",
    cost: "free",
    requiredTier: "free",
    tags: ["fact-check", "us-politics"],
    priority: 55,
  },
  {
    slug: "full-fact",
    name: "Full Fact",
    url: "https://fullfact.org/",
    description: "UK independent fact-checking charity.",
    descriptionTr: "UK bağımsız fact-checking.",
    integrationType: "link",
    category: "fact-check",
    scope: "COUNTRY",
    countryCode: "GB",
    cost: "free",
    requiredTier: "free",
    tags: ["fact-check"],
    priority: 50,
  },
  {
    slug: "captainfact",
    name: "CaptainFact",
    url: "https://captainfact.io/",
    description: "Collaborative fact-checking platform with open API.",
    descriptionTr: "Açık API'li kolaboratif fact-checking platformu.",
    integrationType: "link",
    category: "fact-check",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["fact-check", "collaborative"],
    priority: 40,
  },
  {
    slug: "verification-handbook",
    name: "Verification Handbook",
    url: "https://verificationhandbook.com/",
    description: "DataJournalism verification methodology guide.",
    descriptionTr: "Doğrulama metodoloji kılavuzu.",
    integrationType: "link",
    category: "fact-check",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["methodology", "training"],
    priority: 45,
  },

  // ── Telegram tools ──
  {
    slug: "telegago",
    name: "Telegago",
    url: "https://cse.google.com/cse?cx=006368593537057042503:efxu7xprihg",
    description: "Google CSE indexing 700k+ Telegram channels.",
    descriptionTr: "700k+ Telegram kanalını indexleyen Google CSE.",
    integrationType: "link",
    category: "telegram",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["search", "channels"],
    priority: 80,
  },
  {
    slug: "tgram-search",
    name: "TgramSearch",
    url: "https://tgramsearch.com/",
    description: "Telegram channel and message search engine.",
    descriptionTr: "Telegram kanal ve mesaj arama motoru.",
    integrationType: "link",
    category: "telegram",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["search"],
    priority: 70,
  },
  {
    slug: "telesearch",
    name: "TeleSearch",
    url: "https://telesearch.me/",
    description: "Telegram search aggregator.",
    descriptionTr: "Telegram arama aggregator'ı.",
    integrationType: "link",
    category: "telegram",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["search"],
    priority: 50,
  },
  {
    slug: "teleteg",
    name: "Teleteg",
    url: "https://teleteg.com/",
    description: "Telegram channel directory and analytics.",
    descriptionTr: "Telegram kanal dizini ve analizi.",
    integrationType: "link",
    category: "telegram",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["directory", "analytics"],
    priority: 45,
  },
  {
    slug: "tg-world",
    name: "tg.world",
    url: "https://tg.world/",
    description: "Telegram channel discovery by topic.",
    descriptionTr: "Konu bazlı Telegram kanal keşfi.",
    integrationType: "link",
    category: "telegram",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["discovery"],
    priority: 40,
  },
  {
    slug: "tosint",
    name: "TOsint",
    url: "https://github.com/drego85/tosint",
    description: "Open-source Telegram OSINT CLI tool.",
    descriptionTr: "Açık kaynak Telegram OSINT CLI aracı.",
    integrationType: "link",
    category: "telegram",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["cli", "open-source"],
    priority: 35,
  },

  // ── Social media ──
  {
    slug: "social-searcher",
    name: "Social Searcher",
    url: "https://www.social-searcher.com/",
    description: "Real-time social media search engine.",
    descriptionTr: "Canlı sosyal medya arama motoru.",
    integrationType: "link",
    category: "social",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["search", "monitoring"],
    priority: 60,
  },
  {
    slug: "brandwatch",
    name: "Brandwatch",
    url: "https://www.brandwatch.com/",
    description: "Enterprise social listening and analytics.",
    descriptionTr: "Kurumsal sosyal dinleme ve analiz.",
    integrationType: "link",
    category: "social",
    scope: "GLOBAL",
    cost: "paid",
    requiredTier: "free",
    tags: ["enterprise", "analytics"],
    priority: 50,
  },
  {
    slug: "buzzsumo",
    name: "BuzzSumo",
    url: "https://buzzsumo.com/",
    description: "Content performance and influencer analytics.",
    descriptionTr: "İçerik performansı ve influencer analizi.",
    integrationType: "link",
    category: "social",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["content", "trends"],
    priority: 45,
  },
  {
    slug: "audiense",
    name: "Audiense",
    url: "https://www.audiense.com/",
    description: "Twitter/X audience intelligence and segmentation.",
    descriptionTr: "Twitter/X kitle istihbaratı ve segmentasyonu.",
    integrationType: "link",
    category: "social",
    scope: "GLOBAL",
    cost: "paid",
    requiredTier: "free",
    tags: ["twitter", "audience"],
    priority: 35,
  },
  {
    slug: "tagboard",
    name: "Tagboard",
    url: "https://tagboard.com/",
    description: "Hashtag and social content curation.",
    descriptionTr: "Hashtag ve sosyal içerik küratörlüğü.",
    integrationType: "link",
    category: "social",
    scope: "GLOBAL",
    cost: "paid",
    requiredTier: "free",
    tags: ["hashtag", "curation"],
    priority: 30,
  },
  {
    slug: "epieos",
    name: "Epieos",
    url: "https://epieos.com/",
    description: "Email and phone lookup across services.",
    descriptionTr: "Servisler arası e-posta ve telefon araması.",
    integrationType: "link",
    category: "social",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["lookup", "identity"],
    priority: 40,
  },
  {
    slug: "idcrawl",
    name: "IDCrawl",
    url: "https://www.idcrawl.com/",
    description: "Multi-platform person search engine.",
    descriptionTr: "Çoklu-platform kişi arama motoru.",
    integrationType: "link",
    category: "social",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["lookup", "people"],
    priority: 35,
  },

  // ── Geospatial ──
  {
    slug: "google-earth-pro",
    name: "Google Earth Pro",
    url: "https://www.google.com/intl/en/earth/versions/",
    description: "3D global imagery viewer with historical layers.",
    descriptionTr: "Tarihsel katmanlı 3D global görüntü izleyici.",
    integrationType: "link",
    category: "geospatial",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["imagery", "3d"],
    priority: 80,
  },
  {
    slug: "wikimapia",
    name: "Wikimapia",
    url: "https://wikimapia.org/",
    description: "Community-annotated world map.",
    descriptionTr: "Topluluk-anotasyonlu dünya haritası.",
    integrationType: "link",
    category: "geospatial",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["annotation", "community"],
    priority: 50,
  },
  {
    slug: "mapchart",
    name: "Mapchart.net",
    url: "https://mapchart.net/",
    description: "Create custom-coloured world and country maps.",
    descriptionTr: "Özel-renklendirilmiş dünya/ülke haritaları üret.",
    integrationType: "link",
    category: "geospatial",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["map-creation"],
    priority: 30,
  },
  {
    slug: "mapillary",
    name: "Mapillary",
    url: "https://www.mapillary.com/",
    description: "Crowd-sourced street-level imagery.",
    descriptionTr: "Kitle kaynaklı sokak görüntüleri.",
    integrationType: "link",
    category: "geospatial",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["street-view"],
    priority: 45,
  },
  {
    slug: "kartaview",
    name: "KartaView",
    url: "https://kartaview.org/",
    description: "Open-source street-imagery alternative.",
    descriptionTr: "Açık kaynak sokak görüntüsü alternatifi.",
    integrationType: "link",
    category: "geospatial",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["street-view", "open-source"],
    priority: 40,
  },
  {
    slug: "osint-map-cipher387",
    name: "Worldwide OSINT Tools Map",
    url: "https://cipher387.github.io/osintmap/",
    description: "Visual directory of OSINT tools by country.",
    descriptionTr: "OSINT araçlarının ülke-bazlı görsel dizini.",
    integrationType: "link",
    category: "other",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["directory", "map"],
    priority: 55,
  },

  // ── Cyber search / scanning ──
  {
    slug: "zoomeye",
    name: "ZoomEye",
    url: "https://www.zoomeye.ai/",
    description: "Cyberspace asset search engine.",
    descriptionTr: "Siber uzay varlık arama motoru.",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["scanning"],
    priority: 55,
  },
  {
    slug: "fofa",
    name: "FOFA",
    url: "https://en.fofa.info/",
    description: "Chinese internet-asset search engine.",
    descriptionTr: "Çin menşeili internet-varlık arama motoru.",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["scanning"],
    priority: 50,
  },
  {
    slug: "netlas",
    name: "Netlas.io",
    url: "https://app.netlas.io/",
    description: "Internet-wide attack surface scanner.",
    descriptionTr: "İnternet çapında saldırı yüzeyi tarayıcı.",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["scanning"],
    priority: 45,
  },
  {
    slug: "criminalip",
    name: "Criminal IP",
    url: "https://www.criminalip.io/",
    description: "Threat intelligence for IPs and domains.",
    descriptionTr: "IP ve domain için tehdit istihbaratı.",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["threat-intel"],
    priority: 40,
  },
  {
    slug: "pulsedive",
    name: "Pulsedive",
    url: "https://pulsedive.com/",
    description: "Threat intelligence and IOC enrichment.",
    descriptionTr: "Tehdit istihbaratı ve IOC zenginleştirme.",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["ioc"],
    priority: 40,
  },
  {
    slug: "hybrid-analysis",
    name: "Hybrid Analysis",
    url: "https://www.hybrid-analysis.com/",
    description: "Free malware analysis sandbox.",
    descriptionTr: "Ücretsiz kötücül yazılım analiz sandbox'ı.",
    integrationType: "link",
    category: "cyber",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["sandbox", "malware"],
    priority: 45,
  },

  // ── Data portals ──
  {
    slug: "cia-world-factbook",
    name: "CIA World Factbook",
    url: "https://www.cia.gov/the-world-factbook/",
    description: "Country profiles and reference data.",
    descriptionTr: "Ülke profilleri ve referans verisi.",
    integrationType: "link",
    category: "data",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["reference", "countries"],
    priority: 50,
  },
  {
    slug: "data-gov-uk",
    name: "Data.gov.uk",
    url: "https://data.gov.uk/",
    description: "UK government open data portal.",
    descriptionTr: "UK hükümet açık veri portalı.",
    integrationType: "link",
    category: "data",
    scope: "COUNTRY",
    countryCode: "GB",
    cost: "free",
    requiredTier: "free",
    tags: ["open-data"],
    priority: 30,
  },
  {
    slug: "eu-open-data",
    name: "EU Open Data Portal",
    url: "https://open-data.europa.eu/",
    description: "European Union open data.",
    descriptionTr: "Avrupa Birliği açık verisi.",
    integrationType: "link",
    category: "data",
    scope: "REGION",
    region: "europe",
    cost: "free",
    requiredTier: "free",
    tags: ["open-data"],
    priority: 35,
  },
  {
    slug: "aws-public-datasets",
    name: "AWS Public Datasets",
    url: "https://aws.amazon.com/datasets",
    description: "Large-scale public datasets on S3.",
    descriptionTr: "S3 üzerinde büyük ölçekli açık veri setleri.",
    integrationType: "link",
    category: "data",
    scope: "GLOBAL",
    cost: "freemium",
    requiredTier: "free",
    tags: ["big-data"],
    priority: 25,
  },
  {
    slug: "bis-statistics",
    name: "BIS Statistics",
    url: "https://www.bis.org/statistics/index.htm",
    description: "Bank for International Settlements macro-financial data.",
    descriptionTr: "BIS makro-finansal verisi.",
    integrationType: "link",
    category: "data",
    scope: "GLOBAL",
    cost: "free",
    requiredTier: "free",
    tags: ["finance", "macro"],
    priority: 30,
  },

  // ── Wire services ──
  {
    slug: "afp",
    name: "AFP",
    url: "https://www.afp.com/",
    description: "Agence France-Presse wire service.",
    descriptionTr: "Agence France-Presse haber ajansı.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "paid",
    requiredTier: "free",
    tags: ["wire", "agency"],
    priority: 55,
  },
  {
    slug: "ap-news",
    name: "Associated Press",
    url: "https://hosted.ap.org/",
    description: "AP global wire service.",
    descriptionTr: "AP global haber ajansı.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "paid",
    requiredTier: "free",
    tags: ["wire", "agency"],
    priority: 60,
  },
  {
    slug: "reuters",
    name: "Reuters",
    url: "https://www.reuters.com/",
    description: "Reuters news and wire service.",
    descriptionTr: "Reuters haber ve wire servisi.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "paid",
    requiredTier: "free",
    tags: ["wire", "agency"],
    priority: 65,
  },
  {
    slug: "factiva",
    name: "Factiva (Dow Jones)",
    url: "https://www.dowjones.com/factiva",
    description: "Licensed global news archive.",
    descriptionTr: "Lisanslı global haber arşivi.",
    integrationType: "link",
    category: "news",
    scope: "GLOBAL",
    cost: "paid",
    requiredTier: "free",
    tags: ["archive", "enterprise"],
    priority: 30,
  },
  {
    slug: "itar-tass",
    name: "TASS",
    url: "https://tass.com/",
    description: "Russian news agency.",
    descriptionTr: "Rus haber ajansı.",
    integrationType: "link",
    category: "news",
    scope: "REGION",
    region: "russia",
    cost: "free",
    requiredTier: "free",
    tags: ["wire", "russia"],
    priority: 35,
  },
];
